### ISSUE TITLE
DRAM setup.py errror: TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Edward-Tristan** [WrightonLabCSU/DRAM#113]
Hi Mike,

I tried to solve the last error and modified the download url, but there appear other errors , please see below

(viral-id-sop) [huqy@login1 ~]$ DRAM-setup.py prepare_databases --skip_uniref --output_dir db-dramv --threads 10
2021-09-04 16:42:34.995573: Database preparation started
1:19:38.829150: PFAM database processed
1:19:53.368167: dbCAN database processed
1:20:33.256943: RefSeq viral database processed
1:21:56.888479: MEROPS database processed
1:25:14.577077: VOGdb database processed
1:32:02.532440: KOfam database processed
1:32:05.453576: KOfam ko list processed
1:32:10.737032: PFAM hmm dat processed
1:32:12.838330: dbCAN fam activities processed
1:32:15.066984: VOGdb annotations processed
Traceback (most recent call last):
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 496, in prepare_databases
    output_dbs['genome_summary_form_loc'] = download_and_process_genome_summary_form(temporary, branch, verbose)
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 268, in download_and_process_genome_summary_form
    download_file('https://github.com/shafferm/DRAM/tree/master/data/genome_summary_form.tsv' % branch,
TypeError: not all arguments converted during string formatting

**Comment by rmFlynn** [comment]
This error is related to string formatting not finding a place to insert the variable. If you modify the code to hardcore the branch variable ie delete `%s` and put in `master` you must also delete `% branch`.

**Comment by rmFlynn** [comment]
Looks solved
