### ISSUE TITLE
ERROR in DRAM-setup.py prepare_databases

### ISSUE THREAD

**Issue by caris1988** [WrightonLabCSU/DRAM#133]
Hi developer, 

I met some problem when setup the databases. Since the bad network, I have downloaded all the database files needed, and the run the commond, 
`DRAM-setup.py prepare_databases --verbose --keep_database_files --output_dir /public/home/chenruolin/tools/DRAM-master/dramdb/ --uniref_loc /public/home/chenruolin/tools/data/dramdb/database_files/uniref90.fasta.gz --pfam_loc /public/home/chenruolin/tools/data/dramdb/Pfam-A.full.gz --pfam_hmm_dat /public/home/chenruolin/tools/data/dramdb/Pfam-A.hmm.dat.gz --kofam_hmm_loc /public/home/chenruolin/tools/data/dramdb/profiles.tar.gz --kofam_ko_list_loc /public/home/chenruolin/tools/data/dramdb/kofam_ko_list.tsv.gz --dbcan_loc /public/home/chenruolin/tools/data/dramdb/dbCAN-HMMdb-V9.txt --dbcan_fam_activities /public/home/chenruolin/tools/data/dramdb/CAZyDB.07302020.fam-activities.txt --vogdb_loc /public/home/chenruolin/tools/data/dramdb/vog.hmm.tar.gz --vog_annotations /public/home/chenruolin/tools/data/dramdb/vog.annotations.tsv.gz --viral_loc /public/home/chenruolin/tools/data/dramdb/viral.merged.protein.faa.gz --peptidase_loc /public/home/chenruolin/tools/data/dramdb/pepunit.lib --genome_summary_form_loc data/genome_summary_form.tsv --module_step_form_loc data/module_step_form.tsv --etc_module_database_loc data/etc_module_database.tsv --function_heatmap_form_loc data/function_heatmap_form.tsv --amg_database_loc data/amg_database.tsv`

Then an error occured when creating the description_db, here is the information:

> 2022-01-06 12:02:10.920674: Database preparation started
0:11:19.455148: UniRef database processed
0:52:57.591259: PFAM database processed
0:53:04.150916: dbCAN database processed
0:53:09.096544: RefSeq viral database processed
0:54:00.386160: MEROPS database processed
0:57:11.343257: VOGdb database processed
1:03:06.284816: KOfam database processed
1:03:06.491583: KOfam ko list processed
1:03:06.491636: PFAM hmm dat processed
1:03:06.491654: dbCAN fam activities processed
1:03:06.491664: VOGdb annotations processed
1:03:06.491672: DRAM databases and forms downloaded
1:03:06.655536: Files moved to final destination
1:03:06.656158: Setting database paths
1:03:06.666790: Database locations added to CONFIG
Traceback (most recent call last):
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/public/home/chenruolin/.conda/envs/DRAM/bin/DRAM-setup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/public/home/chenruolin/tools/DRAM-master/scripts/DRAM-setup.py", line 148, in <module>
    args.func(**args_dict)
  File "/public/home/chenruolin/tools/DRAM-master/mag_annotator/database_processing.py", line 526, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/public/home/chenruolin/tools/DRAM-master/mag_annotator/database_processing.py", line 354, in set_database_paths
    populate_description_db(description_db_loc, db_dict, start_time)
  File "/public/home/chenruolin/tools/DRAM-master/mag_annotator/database_processing.py", line 381, in populate_description_db
    create_description_db(db_dict['description_db'])
  File "/public/home/chenruolin/tools/DRAM-master/mag_annotator/database_setup.py", line 137, in create_description_db
    Base.metadata.create_all(engine)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 849, in visit_metadata
    self.traverse_single(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 905, in visit_table
    self.traverse_single(index, create_ok=True)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 936, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: CREATE INDEX ix_kegg_description_id ON kegg_description (id)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

What can I do to solve this problem? Thank  you!

**Comment by rmFlynn** [comment]
It looks like something is wrong with your SQL database, it could be that it is write protected somehow? These issues can be difficult as I think some disk features like syncing can mess with the database. If you have no idea why, do you think you could clone the GitHub repository and run the unit test? They may give us a better idea what is going on.  

Just make sure you are in the same environment Conda/whatever you use to run dram, and run something like:
```
git clone https://github.com/WrightonLabCSU/DRAM.git
cd DRAM
pytest
```
We just upgraded, so you will be a version behind, but it should work still.

**Comment by caris1988** [comment]
Hi rmFlynn, 

Thanks for your kind reply!
I ran the test and got this information:

> ===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /public/home/chenruolin/tools/DRAM
collected 103 items                                                                                                                                                                           
tests/test_annotate_bins.py ......................................                                                                                                                      [ 36%]
tests/test_annotate_vgfs.py ........                                                                                                                                                    [ 44%]
tests/test_database_handler.py ..............                                                                                                                                           [ 58%]
tests/test_database_processing.py ...                                                                                                                                                   [ 61%]
tests/test_database_setup.py .                                                                                                                                                          [ 62%]
tests/test_summarize_genomes.py .........................                                                                                                                               [ 86%]
tests/test_summarize_vgfs.py .......                                                                                                                                                    [ 93%]
tests/test_utils.py .......                                                                                                                                                             [100%]
====================================================================================== warnings summary =======================================================================================
../../.conda/envs/DRAM/lib/python3.9/site-packages/skbio/sequence/_sequence.py:28
  /public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/skbio/sequence/_sequence.py:28: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    collections.Sequence, SkbioObject):
../../.conda/envs/DRAM/lib/python3.9/site-packages/skbio/io/format/gff3.py:217
  /public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/skbio/io/format/gff3.py:217: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Iterable
mag_annotator/summarize_genomes.py:460
  /public/home/chenruolin/tools/DRAM/mag_annotator/summarize_genomes.py:460: DeprecationWarning: invalid escape sequence \d
    axis=alt.Axis(labelLimit=0, labelExpr="replace(datum.label, /_\d*$/gi, '')"))
mag_annotator/summarize_genomes.py:311
  /public/home/chenruolin/tools/DRAM/mag_annotator/summarize_genomes.py:311: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if char is '(':
mag_annotator/summarize_genomes.py:313
  /public/home/chenruolin/tools/DRAM/mag_annotator/summarize_genomes.py:313: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if char is ')':
tests/test_annotate_bins.py: 24 warnings
tests/test_database_processing.py: 11 warnings
  /public/home/chenruolin/.conda/envs/DRAM/lib/python3.9/site-packages/skbio/sequence/_sequence.py:427: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
    return self._bytes.tostring()
tests/test_annotate_bins.py::test_assign_grades
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:261: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [False, 'K00003', False, 'EIORWU234KLKDS', pd.np.NaN],
tests/test_annotate_bins.py::test_assign_grades
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:262: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [False, pd.np.NaN, False, pd.np.NaN, pd.np.NaN],
tests/test_annotate_bins.py::test_assign_grades
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:263: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [False, pd.np.NaN, False, pd.np.NaN, ['PF01235']]]
tests/test_annotate_bins.py::test_assign_grades
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:275: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [False, 'K00003', pd.np.NaN],
tests/test_annotate_bins.py::test_assign_grades
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:276: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [False, pd.np.NaN, pd.np.NaN],
tests/test_annotate_bins.py::test_assign_grades
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:277: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [False, pd.np.NaN, ['PF01235']]]
tests/test_annotate_bins.py::test_run_trna_scan
  /public/home/chenruolin/tools/DRAM/mag_annotator/annotate_bins.py:577: UserWarning: No tRNAs were detected, no trnas.tsv file will be created.
    warnings.warn('No tRNAs were detected, no trnas.tsv file will be created.')
tests/test_annotate_bins.py::test_run_barrnap
  /public/home/chenruolin/tools/DRAM/mag_annotator/annotate_bins.py:598: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
    warnings.warn('No rRNAs were detected, no rrnas.tsv file will be created.')
tests/test_annotate_bins.py::test_annotate_gff
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:451: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    return pd.DataFrame([[pd.np.NaN],
tests/test_annotate_bins.py::test_annotate_gff
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:453: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [pd.np.NaN],
tests/test_annotate_bins.py::test_annotate_gff
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:454: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [pd.np.NaN],
tests/test_annotate_bins.py::test_annotate_gff
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:455: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [pd.np.NaN],
tests/test_annotate_bins.py::test_annotate_gff
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:456: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [pd.np.NaN],
tests/test_annotate_bins.py::test_annotate_gff
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:457: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    [pd.np.NaN]],
tests/test_annotate_bins.py::test_make_trnas_interval
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:714: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    'Note': pd.np.NaN}
tests/test_annotate_bins.py::test_add_intervals_to_gff
  /public/home/chenruolin/tools/DRAM/tests/test_annotate_bins.py:762: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    fake_rrnas = pd.DataFrame([['fake_NC_001422.1', 990, 1000, 101.0, '+', '16S ribosomal rRNA gene', pd.np.NaN]],
tests/test_database_handler.py::test_add_descriptions_to_database
tests/test_database_handler.py::test_get_description
tests/test_database_handler.py::test_get_descriptions
tests/test_database_handler.py::test_get_database_names
tests/test_database_handler.py::test_filter_db_locs
tests/test_database_handler.py::test_export_config
tests/test_database_handler.py::test_print_database_locations
  /public/home/chenruolin/tools/DRAM/mag_annotator/database_handler.py:49: UserWarning: Database does not exist at path None
    warnings.warn('Database does not exist at path %s' % self.description_loc)
tests/test_database_handler.py::test_get_descriptions
  /public/home/chenruolin/tools/DRAM/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this K00003 look like an id from kegg_description
    warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
tests/test_database_handler.py::test_filter_db_locs
  /public/home/chenruolin/tools/DRAM/mag_annotator/database_handler.py:287: UserWarning: Sequences will not be annoated against uniref as it is not configured for use in DRAM
    warnings.warn('Sequences will not be annoated against uniref as it is not configured for use in DRAM')
tests/test_database_handler.py::test_filter_db_locs
  /public/home/chenruolin/tools/DRAM/mag_annotator/database_handler.py:293: UserWarning: Sequences will not be annoated against VOGDB as it is not configured for use in DRAM
    warnings.warn('Sequences will not be annoated against VOGDB as it is not configured for use in DRAM')
tests/test_database_handler.py::test_set_database_paths
tests/test_database_handler.py::test_clear_config
  /public/home/chenruolin/tools/DRAM/mag_annotator/database_handler.py:52: UserWarning: Database does not exist at path None
    warnings.warn('Database does not exist at path %s' % self.description_loc)
tests/test_summarize_genomes.py::test_fill_genome_summary_frame
tests/test_summarize_genomes.py::test_make_genome_summary
  /public/home/chenruolin/tools/DRAM/tests/test_summarize_genomes.py:26: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    ['genome', pd.np.NaN]],
tests/test_summarize_genomes.py::test_summarize_rrnas
  /public/home/chenruolin/tools/DRAM/tests/test_summarize_genomes.py:51: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
    fake_rrnas = pd.DataFrame([['fake_NC_001422.1', 990, 1000, 101.0, '+', '16S rRNA', pd.np.NaN]],
tests/test_summarize_vgfs.py::test_make_viral_distillate
  /public/home/chenruolin/tools/DRAM/mag_annotator/summarize_vgfs.py:123: UserWarning: No distillate information found for gene gene_4
    warnings.warn("No distillate information found for gene %s" % gene)
-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================== 103 passed, 72 warnings in 5040.62s (1:24:00) ========================================================================

I still have no idea why. What should I do next?

Thanks again!

**Comment by rmFlynn** [comment]
My deepest apologies for missing your reply. Also, I am sorry that I don't have any answers for you. I am still stumped. I really thought that the problem with the sql light db would be revealed by the tests, but it looks like you can use that tool. I have many questions, however:

1. Is it possible that your lab use a backup utility that could be interrupting the process? 
2. If you run setup again, do you get the same error? 
3. Is the disk where you are storing the data the same as where you are running these test? 
4. Could the db location be on NAS? Has anyone else in your organization had trouble with sql dbs? 
5. What error do you get if you use the command `DRAM-setup.py update_description_db`

**Comment by genesandatshirt** [comment]
Hello, still have an issue getting DRAM up and running. I've reinstalled DRAM version 1.3.2 successfully with conda method. I run DRAM-setup prepare_databases and I get an error that ends the install:

Traceback (most recent call last):
  File "/home/markowrh/.conda/envs/DRAM/bin/DRAM-setup.py", line 157, in <module>
    args.func(**args_dict)
  File "/home/markowrh/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 343, in populate_description_db
    db_handler.populate_description_db(output_loc)
  File "/home/markowrh/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 234, in populate_description_db
    self.add_descriptions_to_database(self.make_header_dict_from_mmseqs_db(self.db_locs['uniref']) ,
  File "/home/markowrh/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 154, in make_header_dict_from_mmseqs_db
    mmseqs_headers_handle = open('%s_h' % mmseqs_db, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs52/data/bordenstein_lab/rob/interome/DRAM_data/uniref90.20220120.mmsdb_h'


Looking at the files in DRAM_data I can see a uniref90.20220122.mmsdb_h file instead. I assume this is throwing the error but not sure why the version dates are not the same.

**Comment by rmFlynn** [comment]
@caris1988 I hope it works for you going forward.

@genesandatshirt  I don't know how the dates were messed up, but you can fix this by setting up  a new database, or use `DRAM-setup.py export_config --output_file tmp.txt` fix the date in  tmp.txt then use `DRAM-setup.py import_config --config_loc tmp.txt` to reload it.

**Comment by Aiswarya-prasad** [comment]
I have a similar issue. As there doesn't seem to be a resolution that I could try, I am posting here. Here is what my log file contains.

```
Activating conda environment: ../built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb
2022-12-09 19:21:34,690 - The log file is created at 08_DRAM_annotations/ORFs/D2.1/annotate.log
2022-12-09 19:21:34,723 - 1 fastas found
2022-12-09 19:21:34,723 - Checking for duplicate names
2022-12-09 19:21:35,241 - No duplicate names found
2022-12-09 19:21:35,241 - Starting the Annotation of Genes with database configuration: 
 there are no settings, the config is corrupted or too old.
2022-12-09 19:21:35,241 - Checking for duplicate names
2022-12-09 19:21:35,241 - No duplicate names found
2022-12-09 19:21:35,244 - Retrieved database locations and descriptions
2022-12-09 19:21:35,245 - Turning genes from prodigal to mmseqs2 db
2022-12-09 19:21:44,084 - Getting hits from kofam
2022-12-10 00:12:48,260 - Getting forward best hits from peptidase
2022-12-10 00:27:14,195 - Getting reverse best hits from peptidase
2022-12-10 00:27:57,085 - Getting descriptions of hits from peptidase
2022-12-10 00:28:05,010 - Getting hits from pfam
2022-12-10 00:33:13,800 - Getting hits from dbCAN
Traceback (most recent call last):
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: dbcan_description.ec

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/bin/DRAM.py", line 207, in <module>
    args.func(**args_dict)
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1039, in annotate_called_genes_cmd
    annotate_called_genes(fasta_locs, output_dir, bit_score_threshold, rbh_bit_score_threshold,
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1110, in annotate_called_genes
    annotations = annotate_orfs(fasta_loc, db_handler, fasta_dir, logger, custom_db_locs, custom_hmm_locs,
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 738, in annotate_orfs
    annotation_list.append(run_hmmscan(genes_faa=gene_faa,
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/utils.py", line 210, in run_hmmscan
    return formater(hits)
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 208, in dbcan_hmmscan_formater
    hits_df[f"{db_name}_hits"] = hits_df[f"{db_name}_ids"].apply(description_pull)
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/pandas/core/apply.py", line 1105, in apply
    return self.apply_standard()
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/pandas/core/apply.py", line 1156, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2918, in pandas._libs.lib.map_infer
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 204, in description_pull
    description_list = db_handler.get_descriptions(id_list, 'dbcan_description').values()
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 165, in get_descriptions
    descriptions = [
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 168, in <listcomp>
    for des in self.session.query(description_class).filter(description_class.id.in_(chunk)).all()
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2772, in all
    return self._iter().all()
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2915, in _iter
    result = self.session.execute(
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/scratch/aprasad/built-envs/c3f4ddf27d9ffb97971f75ccc4bdf6bb/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: dbcan_description.ec
[SQL: SELECT dbcan_description.id AS dbcan_description_id, dbcan_description.description AS dbcan_description_description, dbcan_description.ec AS dbcan_description_ec 
FROM dbcan_description 
WHERE dbcan_description.id IN (?)]
[parameters: ('GT4',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
To answer some of your earlier questions,
Is it possible that your lab use a backup utility that could be interrupting the process?
If you run setup again, do you get the same error?
Is the disk where you are storing the data the same as where you are running these test?
Could the db location be on NAS? Has anyone else in your organization had trouble with sql dbs?
What error do you get if you use the command DRAM-setup.py update_description_db
