### ISSUE TITLE
Database setup error, but config makes it look like its fine

### ISSUE THREAD

**Issue by jamesck2** [WrightonLabCSU/DRAM#138]
Hi all, I'm having a similar issue that hasn't been resolved. I've tried running DRAM-setup.py twice with this batch command:

```
#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=********@********.***
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=12:00:00
#SBATCH --mem=500gb
#SBATCH --partition=largememory
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=DRAM-database
#SBATCH --output=DRAM-database.out
#SBATCH --error=DRAM-database.err

######  Module commands #####
module load anaconda/python3.8/2020.07

######  Job commands go below this line #####
cd /N/slate/jakosmo

source activate DRAM

DRAM-setup.py prepare_databases --output_dir /N/slate/jakosmo/DRAM_data
DRAM-setup.py print_config
```

And the output text file displays this:

```
2022-01-23 10:34:07.057045: Database preparation started
Processed search databases
KEGG db: None
KOfam db: /N/slate/jakosmo/DRAM_data/kofam_profiles.hmm
KOfam KO list: /N/slate/jakosmo/DRAM_data/kofam_ko_list.tsv
UniRef db: /N/slate/jakosmo/DRAM_data/uniref90.20220122.mmsdb
Pfam db: /N/slate/jakosmo/DRAM_data/pfam.mmspro
dbCAN db: /N/slate/jakosmo/DRAM_data/dbCAN-HMMdb-V9.txt
RefSeq Viral db: /N/slate/jakosmo/DRAM_data/refseq_viral.20220123.mmsdb
MEROPS peptidase db: /N/slate/jakosmo/DRAM_data/peptidases.20220123.mmsdb
VOGDB db: /N/slate/jakosmo/DRAM_data/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: /N/slate/jakosmo/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN family activities: /N/slate/jakosmo/DRAM_data/CAZyDB.07302020.fam-activities.txt
VOG annotations: /N/slate/jakosmo/DRAM_data/vog_annotations_latest.tsv.gz

Description db: /N/slate/jakosmo/DRAM_data/description_db.sqlite

DRAM distillation sheets
Genome summary form: /N/slate/jakosmo/DRAM_data/genome_summary_form.20220123.tsv
Module step form: /N/slate/jakosmo/DRAM_data/module_step_form.20220123.tsv
ETC module database: /N/slate/jakosmo/DRAM_data/etc_mdoule_database.20220123.tsv
Function heatmap form: /N/slate/jakosmo/DRAM_data/function_heatmap_form.20220123.tsv
AMG database: /N/slate/jakosmo/DRAM_data/amg_database.20220123.tsv
```

However, I am getting this error in the error file which is preventing me from successfully being able to run DRAM-v.py:

```
Traceback (most recent call last):
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/bin/DRAM-setup.py", line 157, in <module>
    args.func(**args_dict)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 289, in prepare_databases
    output_dbs['uniref_db_loc'] = download_and_process_uniref(uniref_loc, temporary, uniref_version=uniref_version,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 91, in download_and_process_uniref
    make_mmseqs_db(uniref_fasta_zipped, uniref_mmseqs_db, create_index=True, threads=threads, verbose=verbose)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 38, in make_mmseqs_db
    run_process(['mmseqs', 'createindex', output_loc, tmp_dir, '--threads', str(threads)], verbose=verbose)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createindex', '/N/slate/jakosmo/DRAM_data/database_files/uniref90.20220123.mmsdb', '/N/slate/jakosmo/DRAM_data/database_files/tmp', '--threads', '10']' returned non-zero exit status 1.
```

I don't know if manually downloading the viral protein database from refseq as mentioned above helped @yulong0827 , but would trying the same thing with UniRef help? How would I go about that? Or is there perhaps another solution? Thanks in advance, please advise.

_Originally posted by @jamesck2 in https://github.com/WrightonLabCSU/DRAM/issues/80#issuecomment-1019541815_

**Comment by rmFlynn** [comment]
If you see my response to your past comment please post your results here.

**Comment by jamesck2** [comment]
This was what resulted. I ran this on one compute node with 1 task per node, 16 CPUs per task, and 312gb of memory per node. perhaps I should try again with more memory and more CPUs?

```
createindex /N/slate/jakosmo/DRAM_data/database_files/uniref90.20220123.mmsdb /N/slate/jakosmo/DRAM_data/database_files/tmp 

MMseqs Version:          	13.45111
Seed substitution matrix 	nucl:nucleotide.out,aa:VTML80.out
k-mer length             	0
Alphabet size            	nucl:5,aa:21
Compositional bias       	1
Max sequence length      	65535
Max results per query    	300
Mask residues            	1
Mask lower case residues 	0
Spaced k-mers            	1
Spaced k-mer pattern     	
Sensitivity              	7.5
k-score                  	0
Check compatible         	0
Search type              	0
Split database           	0
Split memory limit       	0
Verbosity                	3
Threads                  	24
Min codons in orf        	30
Max codons in length     	32734
Max orf gaps             	2147483647
Contig start mode        	2
Contig end mode          	2
Orf start mode           	1
Forward frames           	1,2,3
Reverse frames           	1,2,3
Translation table        	1
Translate orf            	0
Use all table starts     	false
Offset of numeric ids    	0
Create lookup            	0
Compressed               	0
Add orf stop             	false
Overlap between sequences	0
Sequence split mode      	1
Header split mode        	0
Strand selection         	1
Remove temporary files   	false

createindex /N/slate/jakosmo/DRAM_data/database_files/uniref90.20220123.mmsdb /N/slate/jakosmo/DRAM_data/database_files/tmp 

MMseqs Version:          	13.45111
Seed substitution matrix 	nucl:nucleotide.out,aa:VTML80.out
k-mer length             	0
Alphabet size            	nucl:5,aa:21
Compositional bias       	1
Max sequence length      	65535
Max results per query    	300
Mask residues            	1
Mask lower case residues 	0
Spaced k-mers            	1
Spaced k-mer pattern     	
Sensitivity              	7.5
k-score                  	0
Check compatible         	0
Search type              	0
Split database           	0
Split memory limit       	0
Verbosity                	3
Threads                  	24
Min codons in orf        	30
Max codons in length     	32734
Max orf gaps             	2147483647
Contig start mode        	2
Contig end mode          	2
Orf start mode           	1
Forward frames           	1,2,3
Reverse frames           	1,2,3
Translation table        	1
Translate orf            	0
Use all table starts     	false
Offset of numeric ids    	0
Create lookup            	0
Compressed               	0
Add orf stop             	false
Overlap between sequences	0
Sequence split mode      	1
Header split mode        	0
Strand selection         	1
Remove temporary files   	false

indexdb /N/slate/jakosmo/DRAM_data/database_files/uniref90.20220123.mmsdb /N/slate/jakosmo/DRAM_data/database_files/uniref90.20220123.mmsdb --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --alph-size nucl:5,aa:21 --comp-bias-corr 1 --max-seq-len 65535 --max-seqs 300 --mask 1 --mask-lower-case 0 --spaced-kmer-mode 1 -s 7.5 --k-score 0 --check-compatible 0 --search-type 0 --split 0 --split-memory-limit 0 -v 3 --threads 24 

Target split mode. Searching through 2 splits
Estimated memory consumption: 240G
Write VERSION (0)
Write META (1)
Write SCOREMATRIX3MER (4)
Write SCOREMATRIX2MER (3)
Write SCOREMATRIXNAME (2)
Write SPACEDPATTERN (23)
Write GENERATOR (22)
Write DBR1INDEX (5)
Write DBR1DATA (6)
Write HDR1INDEX (18)
Write HDR1DATA (19)
Index table: counting k-mers
[=================================================================] 69.24M 6m 25s 511ms
Index table: Masked residues: 443786580
Index table: fill
[=================================================================] 69.24M 7m 23s 778ms
Index statistics
Entries:          21856536966
DB size:          134829 MB
Avg k-mer size:   17.075420
Top 10 k-mers
    SGQQRIA	147681
    GPGGKLL	141408
    YTGTGKG	96758
    DFEQLPH	80005
    NVPGWSP	79950
    FRYAFPS	79834
    RYYVLGW	79804
    GGQRVAR	76703
    TVDGDFS	76632
    QDWVQIP	75356
Write ENTRIES (9)
Write ENTRIESOFFSETS (10)
Write SEQINDEXDATASIZE (15)
Write SEQINDEXSEQOFFSET (16)
Write SEQINDEXDATA (14)
Error: indexdb died
```

**Comment by rmFlynn** [comment]
I think this is a mmseqs error, and you should look on their GitHub, https://github.com/soedinglab/MMseqs2 although when I looked I did not see anything like this exactly.   Try just increasing memory, not cores, mmseqs uses more memory with more threads. A manual download may help also, I would give that a try if I were you. Also, you can try the same command on any file that is in your config and ends in mmsdb, to see if the tool works, make the output a new place to avoid collision. Also, run `DRAM-setup.py version` and double check it is 1.3.2.

**Comment by jamesck2** [comment]
Ok, I will run the same command on fewer cores with 500gb RAM, I will advise once I have the output. I do in fact have DRAM v 1.3.2 installed. Also, when you mention a manual download, do you mean a manual installation of MMseqs2 as instructed by their github page, or do you mean running `mmseqs databases` in my activated DRAM environment? Thanks again for your help with this.

**Comment by rmFlynn** [comment]
It is possible that your database is corrupted.  If you download the uniref database with wget you may be able to run the same command on that database.

**Comment by jamesck2** [comment]
Okay, I ran these commands within my DRAM environment:

```
wget https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz
mmseqs createdb uniref90.fasta.gz uniref90.20220123.mmsdb --createdb-mode 1
mmseqs createindex /N/slate/jakosmo/DRAM_data/uniref90.20220123.mmsdb /N/slate/jakosmo/DRAM_data/tmp
```

They all were successful and no error resulted... that's assuring! This is the output:

```
Top 10 k-mers
    YTGTGKG     181768
    GEGGFVA     109429
    LNAEAAG     82399
    GRFVVEV     76617
    LLGPGKT     71523
    IAQNLLN     68835
    LAMHETP     67127
    RAEGRAV     64635
    FLNSHRT     56031
    ALGSGKS     49210
Write ENTRIES (9)
Write ENTRIESOFFSETS (10)
Write SEQINDEXDATASIZE (15)
Write SEQINDEXSEQOFFSET (16)
Write SEQINDEXDATA (14)
Write ENTRIESNUM (12)
Write SEQCOUNT (13)
Index table: counting k-mers
[=================================================================] 107.05M 30m 11s 176ms
Index table: Masked residues: 299021294
Index table: fill
[=================================================================] 107.05M 36m 8s 401ms
Index statistics
Entries:          21646747566
DB size:          133629 MB
Avg k-mer size:   16.911522
Top 10 k-mers
    GPGGKLL     213611
    GQQVARA     158119
    GGQRVAR     146840
    NVPGWSP     137208
    FRYAFPS     137064
    RYYVLGW     136834
    VDRLNTQ     133187
    WRLDFLN     131564
    TVDGDFS     131438
    QDWVQIP     129530
Write ENTRIES (1009)
Write ENTRIESOFFSETS (1010)
Write SEQINDEXDATASIZE (1015)
Write SEQINDEXSEQOFFSET (1016)
Write SEQINDEXDATA (1014)
Write ENTRIESNUM (1012)
Write SEQCOUNT (1013)
Time for merging to uniref90.20220123.mmsdb.idx: 0h 0m 0s 28ms
Time for processing: 2h 31m 53s 260ms
```

And this is what my DRAM_data direcotry looks like:
<img width="1124" alt="Screen Shot 2022-01-27 at 11 55 22 AM" src="https://user-images.githubusercontent.com/68616716/151416122-bc52e11c-55f2-48a8-9f43-da0e74cbf2f2.png">

And as a sanity check, I ran `DRAM-setup.py print_config` again:
```
Processed search databases
KEGG db: None
KOfam db: /N/slate/jakosmo/DRAM_data/kofam_profiles.hmm
KOfam KO list: /N/slate/jakosmo/DRAM_data/kofam_ko_list.tsv
UniRef db: /N/slate/jakosmo/DRAM_data/uniref90.20220122.mmsdb
Pfam db: /N/slate/jakosmo/DRAM_data/pfam.mmspro
dbCAN db: /N/slate/jakosmo/DRAM_data/dbCAN-HMMdb-V9.txt
RefSeq Viral db: /N/slate/jakosmo/DRAM_data/refseq_viral.20220123.mmsdb
MEROPS peptidase db: /N/slate/jakosmo/DRAM_data/peptidases.20220123.mmsdb
VOGDB db: /N/slate/jakosmo/DRAM_data/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: /N/slate/jakosmo/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN family activities: /N/slate/jakosmo/DRAM_data/CAZyDB.07302020.fam-activities.txt
VOG annotations: /N/slate/jakosmo/DRAM_data/vog_annotations_latest.tsv.gz

Description db: /N/slate/jakosmo/DRAM_data/description_db.sqlite

DRAM distillation sheets
Genome summary form: /N/slate/jakosmo/DRAM_data/genome_summary_form.20220123.tsv
Module step form: /N/slate/jakosmo/DRAM_data/module_step_form.20220123.tsv
ETC module database: /N/slate/jakosmo/DRAM_data/etc_mdoule_database.20220123.tsv
Function heatmap form: /N/slate/jakosmo/DRAM_data/function_heatmap_form.20220123.tsv
AMG database: /N/slate/jakosmo/DRAM_data/amg_database.20220123.tsv
```

I hope this fixes the issue. I will attempt running DRAM-v again and I will let you know how it goes. Does all of this look alright to you? Thank you.

**Comment by jamesck2** [comment]
UPDATE: Now it looks like the database error was solved, but a new error has resulted while running DRAM-v:
```
/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:80: UserWarning: No descriptions were found for your id's. Does this YP_003969738.1 look like an id from viral_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 473, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1007, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 915, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 809, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 679, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]
KeyError: 'YP_003969738.1'
Traceback (most recent call last):
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/summarize_vgfs.py", line 219, in summarize_vgfs
    annotations = pd.read_csv(input_file, sep='\t', index_col=0).fillna('')
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'annotation/annotations.tsv'
```

Would you like to continue here or move over to [this thread](https://github.com/WrightonLabCSU/DRAM/issues/72) that presents a simialr issue?
