### ISSUE TITLE
"UserWarning: No descriptions were found for your id's" KeyError

### ISSUE THREAD

**Issue by jamesck2** [WrightonLabCSU/DRAM#141]
Hello again, my other database issue has been resolved but now I've encountered a different issue with DRAM-v, similar to the one presented in [this thread](https://github.com/WrightonLabCSU/DRAM/issues/72). It looks like it's related to the database again but this time a protein ID isn't being found. Perhaps the protein database files are corrupted? They all appear to be there and full of information. 

Input commands:
```
DRAM-v.py annotate -i ./final-viral-combined-for-dramv.fa -v viral-affi-contigs-for-dramv.tab -o annotation
DRAM-v.py distill -i annotation/annotations.tsv -o annotation/distilled
```

Error file text:
```
/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:80: UserWarning: No descriptions were found for your id's. Does this YP_003969738.1 look like an id from viral_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 473, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1007, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 915, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 809, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 679, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]
KeyError: 'YP_003969738.1'
Traceback (most recent call last):
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/summarize_vgfs.py", line 219, in summarize_vgfs
    annotations = pd.read_csv(input_file, sep='\t', index_col=0).fillna('')
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/N/u/jakosmo/Carbonate/.conda/envs/DRAM/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'annotation/annotations.tsv'
```

Out file text:
```
2022-01-27 13:47:53.897235: Viral annotation started
0:00:00.042023: Retrieved database locations and descriptions
0:00:00.042079: Annotating final-viral-combined-for-dramv
0:00:22.658186: Turning genes from prodigal to mmseqs2 db
0:00:28.338091: Getting hits from kofam
0:24:58.043100: Getting forward best hits from viral
0:26:19.255162: Getting reverse best hits from viral
0:26:29.439230: Getting descriptions of hits from viral
```

**Comment by jamesck2** [comment]
UPDATE: posting this in case other people had the same issue.
It appeared that the sequence YP_003969738.1 which was leading to the key error is a refseq ID that is not in the `refseq_viral.20220123.mmsdb` database created by mmseqs in my `DRAM_data `directory. Since my uniref90 database was corrupted in my last issue and manually downloading/creating the database fixed that, I assumed that my refseq_viral database was corrupted too. So, I used `wget` to obtain the refseq viral .faa files (1-4) from https://ftp.ncbi.nlm.nih.gov/refseq/release/viral/ , decombressed them, concatenated the files together into one file named `refseq_viral.20220123.faa`, and ran `mmseqs createdb refseq_viral.20220123.faa refseq_viral.20220123.mmsdb --createdb-mode 1` followed by `mmseqs createindex /N/slate/jakosmo/DRAM_data/refseq_viral.20220123.mmsdb /N/slate/jakosmo/DRAM_data/tmp` in a large-memory compute node. This approached worked when I needed to fix my corrupted uniref database.

The resulting out file:
```
createdb refseq_viral.20220123.faa refseq_viral.20220123.mmsdb --createdb-mode 1 

MMseqs Version:         13.45111
Database type           0
Shuffle input database  true
Createdb mode           1
Write lookup file       1
Offset of numeric ids   0
Compressed              0
Verbosity               3

Shuffle database cannot be combined with --createdb-mode 0
We recompute with --shuffle 0
Converting sequences
[Multiline fasta can not be combined with --createdb-mode 0
We recompute with --createdb-mode 1
Time for merging to refseq_viral.20220123.mmsdb_h: 0h 0m 0s 8ms
Time for merging to refseq_viral.20220123.mmsdb: 0h 0m 0s 25ms
[=========================================================
Time for merging to refseq_viral.20220123.mmsdb_h: 0h 0m 0s 6ms
Time for merging to refseq_viral.20220123.mmsdb: 0h 0m 0s 6ms
Database type: Aminoacid
Time for processing: 0h 0m 2s 197ms
createindex /N/slate/jakosmo/DRAM_data/refseq_viral.20220123.mmsdb /N/slate/jakosmo/DRAM_data/tmp 

MMseqs Version:                 13.45111
Seed substitution matrix        nucl:nucleotide.out,aa:VTML80.out
k-mer length                    0
Alphabet size                   nucl:5,aa:21
Compositional bias              1
Max sequence length             65535
Max results per query           300
Mask residues                   1
Mask lower case residues        0
Spaced k-mers                   1
Spaced k-mer pattern            
Sensitivity                     7.5
k-score                         0
Check compatible                0
Search type                     0
Split database                  0
Split memory limit              0
Verbosity                       3
Threads                         24
Min codons in orf               30
Max codons in length            32734
Max orf gaps                    2147483647
Contig start mode               2
Contig end mode                 2
Orf start mode                  1
Forward frames                  1,2,3
Reverse frames                  1,2,3
Translation table               1
Translate orf                   0
Use all table starts            false
Offset of numeric ids           0
Create lookup                   0
Compressed                      0
Add orf stop                    false
Overlap between sequences       0
Sequence split mode             1
Header split mode               0
Strand selection                1
Remove temporary files          false

createindex /N/slate/jakosmo/DRAM_data/refseq_viral.20220123.mmsdb /N/slate/jakosmo/DRAM_data/tmp 

MMseqs Version:                 13.45111
Seed substitution matrix        nucl:nucleotide.out,aa:VTML80.out
k-mer length                    0
Alphabet size                   nucl:5,aa:21
Compositional bias              1
Max sequence length             65535
Max results per query           300
Mask residues                   1
Mask lower case residues        0
Spaced k-mers                   1
Spaced k-mer pattern            
Sensitivity                     7.5
k-score                         0
Check compatible                0
Search type                     0
Split database                  0
Split memory limit              0
Verbosity                       3
Threads                         24
Min codons in orf               30
Max codons in length            32734
Max orf gaps                    2147483647
Contig start mode               2
Contig end mode                 2
Orf start mode                  1
Forward frames                  1,2,3
Reverse frames                  1,2,3
Translation table               1
Translate orf                   0
Use all table starts            false
Offset of numeric ids           0
Create lookup                   0
Compressed                      0
Add orf stop                    false
Overlap between sequences       0
Sequence split mode             1
Header split mode               0
Strand selection                1
Remove temporary files          false

indexdb /N/slate/jakosmo/DRAM_data/refseq_viral.20220123.mmsdb /N/slate/jakosmo/DRAM_data/refseq_viral.20220123.mmsdb --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --alph-size nucl:5,aa:21 --comp-bias-corr 1 --max-seq-len 65535 --max-seqs 300 --mask 1 --mask-lower-case 0 --spaced-kmer-mode 1 -s 7.5 --k-score 0 --check-compatible 0 --search-type 0 --split 0 --split-memory-limit 0 -v 3 --threads 24 

Estimated memory consumption: 2G
Write VERSION (0)
Write META (1)
Write SCOREMATRIX3MER (4)
Write SCOREMATRIX2MER (3)
Write SCOREMATRIXNAME (2)
Write SPACEDPATTERN (23)
Write GENERATOR (22)
Write DBR1INDEX (5)
Write DBR1DATA (6)
Write HDR1INDEX (18)
Write HDR1DATA (19)
Index table: counting k-mers
[=================================================================] 577.49K 8s 849ms
Index table: Masked residues: 1902938
Index table: fill
[=================================================================] 577.49K 6s 896ms
Index statistics
Entries:          130216283
DB size:          1233 MB
Avg k-mer size:   2.034629
Top 10 k-mers
    SRGTAR      561
    GGPICN      518
    WQNKKP      484
    NHEALY      483
    GKWDIK      462
    HANVTL      461
    MATAPV      459
    YMCHNP      450
    ATKRFY      449
    ACHSVY      444
Write ENTRIES (9)
Write ENTRIESOFFSETS (10)
Write SEQINDEXDATASIZE (15)
Write SEQINDEXSEQOFFSET (16)
Write SEQINDEXDATA (14)
Write ENTRIESNUM (12)
Write SEQCOUNT (13)
Time for merging to refseq_viral.20220123.mmsdb.idx: 0h 0m 0s 17ms
Time for processing: 0h 0m 19s 725ms
```

The .err file was empty and it appears that this was successful. So I went ahead and tried re-running DRAM-v:
```
DRAM-v.py annotate -i ./final-viral-combined-for-dramv.fa -v viral-affi-contigs-for-dramv.tab -o annotation
DRAM-v.py distill -i annotation/annotations.tsv -o annotation/distilled
```

If I get the same error with the refseq database then I will go back and try something different, and if I get a new error then I think I will go back and manually download every component of the database as I did with refseq and uniref. I will update as soon as my job finishes.

**Comment by jamesck2** [comment]
Okay, this seems a bit odd. I got the same error but this time for a protein ID YP_009851069.1 instead of the ID which initially caused the key error at the top (YP_003969738.1). I did `grep -c YP_009851069.1 ../DRAM_data/*` and the ID does in fact appear in the mmseq files:
```
../DRAM_data/refseq_viral.20220123.faa:1
../DRAM_data/refseq_viral.20220123.mmsdb:0
../DRAM_data/refseq_viral.20220123.mmsdb.dbtype:0
../DRAM_data/refseq_viral.20220123.mmsdb_h:1
../DRAM_data/refseq_viral.20220123.mmsdb_h.dbtype:0
../DRAM_data/refseq_viral.20220123.mmsdb_h.index:0
../DRAM_data/refseq_viral.20220123.mmsdb.idx:1
../DRAM_data/refseq_viral.20220123.mmsdb.idx.dbtype:0
../DRAM_data/refseq_viral.20220123.mmsdb.idx.index:0
../DRAM_data/refseq_viral.20220123.mmsdb.index:0
../DRAM_data/refseq_viral.20220123.mmsdb.lookup:1
../DRAM_data/refseq_viral.20220123.mmsdb.source:0
```
I'm not sure why the ID isn't being found.

**Comment by rmFlynn** [comment]
Now that you have replaced those "database" file, you must update your descriptions with `DRAM-setup.py update_description_db`  that should fix the problem

**Comment by jamesck2** [comment]
Ok, I see. I ran that comand and it has been running for over 15 hours now on a large memory node, does this seem usual? There isn't anything in the out or error files so I'm not sure if it is doing anything.

**Comment by rmFlynn** [comment]
It's probably on a remote server, or storing its data on a network attached storage space, this part of the script uses a light SQL database. The reason it sucks here, assuming I'm right about your infrastructure, is that you are opening up a network communication channel for each entry into the database which is insanely slow. If you can run this more locally where the data stored that would be great. Unfortunately it doesn't spit out estimates and these systems often don't write logs until the end because they are also aware of this constraint. It should take 2 to 3 hours 5 hours at most.

**Comment by jamesck2** [comment]
I see, yes I think you are right about that. Unfortunatley I don't think I have something local with enough RAM to do this, although I have about 1TB of local disk space at my disposal. Do you think increasing the number of nodes and tasks per nodes assigned to this job would speed it up?

**Comment by rmFlynn** [comment]
Depressingly no. This part of the script doesn't have multithreading. One of many things we really need to improve. If I were you I would honestly give it a try on your local machine, it doesn't use quite as much RAM as the other parts. If you're really confident it's not going to work then I think you just have to leave it running. If you get a SQL light viewer you can find and look at the database see how many records have been written. You can also use SQL like commands to do this.

**Comment by jamesck2** [comment]
I understand, it is what it is. Luckily, the command ended up finishing after 19 hours. I am going to try running DRAM-v again.

**Comment by jamesck2** [comment]
Ha! It finally worked! DRAM-v ran and I sucessfully obtained the distillation files in about 30 minutes of walltime. Thank you for the help :)

**Comment by JSSaini** [comment]
Same error. @rmFlynn Is there an easy fix to this?

**Comment by rmFlynn** [comment]
Did you run DRAM-setup.py update_description_db?

**Comment by JSSaini** [comment]
I just did a fresh installation, I thought there is no need?

**Comment by rmFlynn** [comment]
You may want to do it anyway also did you check the version? `DRAM-setup.py  version`

**Comment by JSSaini** [comment]
IT WORKED!!!!!!!!! 

DRAM-setup.py version
1.3.2

It needed DRAM-setup.py update_description_db.
