### ISSUE TITLE
tRNAscan-SE exit status 13

### ISSUE THREAD

**Issue by vmkhot** [WrightonLabCSU/DRAM#142]
Hello!

Thanks so much for building such a powerful annotation software!

I've downloaded and set up DRAM with uniref90 and other databases (no kegg) and am running a trial with DRAM using just 1 bin and a trial with DRAMv using contigs/files from virsorter2. The databases seem to be correctly set up according to the "print config"

I'm running the following commands:

`DRAM.py annotate -i './dram_prok/*.fa' -o ./dram_prok/annotation --threads 20`
`DRAM-v.py annotate -i ./dramv/final-viral-combined-for-dramv.fa -v ./dramv/viral-affi-contigs-for-dramv.tab -o ./dramv/annotation --threads 20`

I'm getting the following similar error from both the trials based on the log file :

1 fastas found
2022-02-03 14:36:47.365227: Annotation started
0:00:00.020943: Retrieved database locations and descriptions
0:00:00.020968: Annotating bin12
0:00:40.498152: Turning genes from prodigal to mmseqs2 db
0:00:43.633121: Getting hits from kofam
0:11:28.646734: Getting forward best hits from peptidase
0:11:34.181181: Getting reverse best hits from peptidase
0:11:40.259181: Getting descriptions of hits from peptidase
0:11:40.579308: Getting hits from pfam
0:11:48.383774: Getting hits from dbCAN
0:11:55.672758: Getting hits from VOGDB
0:15:45.367776: Merging ORF annotations
Traceback (most recent call last):
  File "/home/vmkhot/miniconda3/envs/DRAM/bin/DRAM.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/vmkhot/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/home/vmkhot/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1005, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/home/vmkhot/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 923, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/home/vmkhot/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 857, in annotate_fasta
    trna_table = run_trna_scan(renamed_scaffolds, tmp_dir, fasta_name, threads=threads, verbose=verbose)
  File "/home/vmkhot/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 544, in run_trna_scan
    run_process(['tRNAscan-SE', '-G', '-o', raw_trnas, '--thread', str(threads), fasta], verbose=verbose)
  File "/home/vmkhot/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/vmkhot/miniconda3/envs/DRAM/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tRNAscan-SE', '-G', '-o', './dram_prok/annotation/working_dir/bin12/tmp/raw_trnas.txt', '--thread', '20', './dram_prok/annotation/working_dir/bin12/scaffolds.annotated.fa']' returned non-zero exit status 13.

Additionally I checked the path to `./dram_prok/annotation/working_dir/bin12/tmp/raw_trnas.txt` and no such file is exists

I'm not sure what exactly is going wrong in this. Hope I'm not missing anything obvious and your help is very much appreciated! 

Cheers,

Varada

**Comment by rmFlynn** [comment]
In the directory where you ran DRAM, run `tRNAscan-SE -G -o ./dram_prok/annotation/working_dir/bin12/tmp/raw_trnas.txt --thread 20 ./dram_prok/annotation/working_dir/bin12/scaffolds.annotated.fa` that will give a more informative error.

**Comment by vmkhot** [comment]
Hi again,

I ran what you suggested and error showed a perl version incompatibility - which was solved easily. Program runs great now. 

Thanks so much!
