### ISSUE TITLE
distill produces key value error

### ISSUE THREAD

**Issue by ggavelis** [WrightonLabCSU/DRAM#143]
Hi, Per the manual I'm trying this command:

**DRAM.py distill -i** test.fasta **-o** distill **--trna_path** annotation/trnas.tsv **--rrna_path** annotation/rrnas.tsv

And getting the following error:

Traceback (most recent call last):
  File "/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/dram_1.3.2/bin/DRAM.py", line 189, in <module>
    args.func(**args_dict)
  File "/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/dram_1.3.2/lib/python3.9/site-packages/mag_annotator/summarize_genomes.py", line 594, in summarize_genomes
    genome_stats = make_genome_stats(annotations, rrna_frame, trna_frame, groupby_column=groupby_column)
  File "/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/dram_1.3.2/lib/python3.9/site-packages/mag_annotator/summarize_genomes.py", line 158, in make_genome_stats
    for genome, frame in annotations.groupby(groupby_column, sort=False):
  File "/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/dram_1.3.2/lib/python3.9/site-packages/pandas/core/frame.py", line 7714, in groupby
    return DataFrameGroupBy(
  File "/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/dram_1.3.2/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 882, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/dram_1.3.2/lib/python3.9/site-packages/pandas/core/groupby/grouper.py", line 882, in get_grouper
    raise KeyError(gpr)
KeyError: 'fasta'

_______________________________________________________________________________
# CONTEXT
I'm working with DRAM 1.3.2 on an HPC where I lack root privileges.

PRIOR COMMANDS:

1. Install (no errors)
**conda install -c bioconda dram**
**conda activate dram**

2. DB (no errors)
**DRAM-setup.py prepare_databases --output_dir** /mnt/scgc_nfs/ref/full_dram_db/ **--threads 16**

3. Check config
**DRAM-setup.py print_config**
output: [https://pastebin.com/nnY2M8fb](https://pastebin.com/nnY2M8fb)

4. Annotate (no errors, just a warning)
**DRAM.py annotate -i** test.fasta -o annotation

5. Tried to update description db (killed by server without further explanation)
**DRAM-setup.py update_description_db**

Thanks,  ~Greg

**Comment by rmFlynn** [comment]
The input for distill is the annotations.tsv, not a fasta see `DRAM.py distill --help ` for more info.
