### ISSUE TITLE
Checkm & GTDBTK files arguments error

### ISSUE THREAD

**Issue by theo-llewellyn** [WrightonLabCSU/DRAM#144]
Hi, I'm having an issue using checkm and gtdbtk files in my `DRAM.py annotate` command. My command is as follows:
`DRAM.py annotate -i 'metawrap_70_5/*.fa' -o LIQ106LELE_annotation --min_contig_size 1000 --gtdb_taxonomy LIQ106LELE_gtdbtk.bac120.summary.tsv --checkm_quality reassembled_bins_70_5.stats1 --verbose --threads 8`

If I remove the --checkm_quality and --gtdb_taxonomy arguments and files DRAM works normally. The error I get is
```
Traceback (most recent call last):
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/bin/DRAM.py", line 187, in <module>
    args = parser.parse_args()
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 1824, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 1857, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 2048, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 2025, in consume_positionals
    take_action(action, args)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 1934, in take_action
    action(self, namespace, argument_values, option_string)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 1213, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 1857, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 2066, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 2006, in consume_optional
    take_action(action, args, option_string)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 1934, in take_action
    action(self, namespace, argument_values, option_string)
  File "/rds/general/user/tbl19/home/anaconda3/envs/DRAM/lib/python3.9/argparse.py", line 1029, in __call__
    items.append(values)
AttributeError: 'tuple' object has no attribute 'append'
[reassembled_bins_70_5.stats1.txt](https://github.com/WrightonLabCSU/DRAM/files/8033444/reassembled_bins_70_5.stats1.txt)
[LIQ106LELE_gtdbtk.bac120.summary.tsv.txt](https://github.com/WrightonLabCSU/DRAM/files/8033445/LIQ106LELE_gtdbtk.bac120.summary.tsv.txt)

```
I have 6 bins in the directory and the gtdbtk and checkm files are attached. Any idea whats the issue with those files/arguments?
[LIQ106LELE_gtdbtk.bac120.summary.tsv.txt](https://github.com/WrightonLabCSU/DRAM/files/8033483/LIQ106LELE_gtdbtk.bac120.summary.tsv.txt)
[reassembled_bins_70_5.stats1.txt](https://github.com/WrightonLabCSU/DRAM/files/8033484/reassembled_bins_70_5.stats1.txt)

Thanks,
Theo

**Comment by rmFlynn** [comment]
It looks like there is a bug in the command line arguments, I will fix it soon, and let you know.
