### ISSUE TITLE
DRAM-v.py distill question

### ISSUE THREAD

**Issue by miczuppi** [WrightonLabCSU/DRAM#146]
Hi,
I need to run `DRAM-v.py distill` with the `--trna_path` and `--rrna_path` flags on multiple genomes.
The problem is that all these genomes presented RNA genes, and there are no trna.tsv and rrna.tsv files in the DRAMv output, a fact that causes `DRAM-v.py distill` with the `--trna_path` and `--rrna_path` flags to stop running.  

Is there a way to run the `DRAM-v.py distill` on these multiple files so that it includes the RNA genes in the summary if they are present, but does not stop if they aren't?

Thank you for your time,
Michele

**Comment by miczuppi** [comment]
Hi, thank you for the reply. 
I have been trying to follow your command but it gives me this error message:

`Traceback (most recent call last):
  File "/mnt/projects/miniconda2/envs/DRAM/bin/DRAM.py", line 168, in <module>
    args.func(**args_dict)
  File "/mnt/projects/miniconda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1182, in merge_annotations_cmd
    merge_annotations(annotations_list, output_dir, write_annotations=True)
  File "/mnt/projects/miniconda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1127, in merge_annotations
    all_annotations = pd.concat([i.get_annotations() for i in annotations_list if i is not None], sort=False)
  File "/mnt/projects/miniconda2/envs/DRAM/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/mnt/projects/miniconda2/envs/DRAM/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/mnt/projects/miniconda2/envs/DRAM/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
`
Do you know what could be causing it?

**Comment by rmFlynn** [comment]
What is your folder structure like?

**Comment by miczuppi** [comment]
It is `/dramv/all_the_output_folders/`.

**Comment by rmFlynn** [comment]
Hmm, then if /dramv/all_the_output_folders/ contains folder1/annotations.tsv, folder2/annotations.tsv I would have thought it would at least give a more constructive error. I will eventually have time to fix this tool, but for now I am afraid that you will need to combine them manually.

**Comment by rmFlynn** [comment]
Really sorry that was not helpful

**Comment by miczuppi** [comment]
Hi, no worries at all. 
If it can help, I have managed to solve the problem in a probably overly-complicated way. 
```
                find . -mindepth 1 -maxdepth 1 -type d -exec test -e "{}/rrnas.tsv" ';' -print | xargs -I {} -P 10 DRAM.py distill -i {}/annotations.tsv -o {}/genome_summaries --trna_path {}/trnas.tsv --rrna_path {}/rrnas.tsv --distillate_gene_names
                find . -mindepth 1 -maxdepth 1 -type d -exec test -e "{}/trnas.tsv" ';' -print | xargs -I {} -P 10 DRAM.py distill -i {}/annotations.tsv -o {}/genome_summaries --trna_path {}/trnas.tsv --distillate_gene_names
                find . -mindepth 1 -maxdepth 1 -type d -exec test -e "{}/rrnas.tsv" ';' -print | xargs -I {} -P 10 DRAM.py distill -i {}/annotations.tsv -o {}/genome_summaries --rrna_path {}/rrnas.tsv --distillate_gene_names 
                find . -mindepth 1 -maxdepth 1 -type d '!' -exec sh -c 'ls -1 "{}"|egrep -i -q "*rnas.tsv$"' ';' -print  | xargs -I {} -P 10 DRAM.py distill -i {}/annotations.tsv -o {}/genome_summaries --distillate_gene_names 
```
Basically, I run it the *rna distill only on the folders that contains the *rna.tsv files. 
Thank you for your help anyway.

Michele
