### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by cedhahn** [WrightonLabCSU/DRAM#151]
Hi,
I just installed DRAM and try to run an annotation, however I keep running into the following problem:

During the merging of the ORF annotations the process stops with the error message: AttributeError: 'NoneType' object has no attribute 'group'; see log below.
I would be very grateful for tips how to solve this issue! 

```
DRAM.py annotate -i 1.fa -o DRAM --threads 20
1 fastas found
2022-02-20 08:52:24.662602: Annotation started
0:00:00.016482: Retrieved database locations and descriptions
0:00:00.016535: Annotating Ethanoperedens-contigs
0:00:22.919430: Turning genes from prodigal to mmseqs2 db
0:00:26.488266: Getting forward best hits from kegg
0:01:31.017504: Getting reverse best hits from kegg
0:01:44.793400: Getting descriptions of hits from kegg
0:01:44.862990: Getting forward best hits from peptidase
0:01:51.021754: Getting reverse best hits from peptidase
0:01:54.114865: Getting descriptions of hits from peptidase
0:01:54.124684: Getting hits from pfam
0:02:08.280415: Getting hits from dbCAN
/bioinf/home/chahn/software/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:80: UserWarning: No descriptions were found for your id's. Does this cohesin look like an id from dbcan_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
/bioinf/home/chahn/software/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:80: UserWarning: No descriptions were found for your id's. Does this GT2_Glycos_transf_2 look like an id from dbcan_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
0:04:56.336811: Merging ORF annotations
Traceback (most recent call last):
  File "/bioinf/home/chahn/software/miniconda3/envs/DRAM/bin/DRAM.py", line 189, in <module>
    args.func(**args_dict)
  File "/bioinf/home/chahn/software/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1034, in annotate_bins_cmd
    annotate_bins(list(set(fasta_locs)), output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/bioinf/home/chahn/software/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1073, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/bioinf/home/chahn/software/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1007, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/bioinf/home/chahn/software/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 937, in annotate_fasta
    annotate_gff(gene_gff, renamed_gffs, annotations, prefix=prefix)
  File "/bioinf/home/chahn/software/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 485, in annotate_gff
    gene_number = match.group().split('_')[-1][:-1]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by cedhahn** [comment]
Thanks for your reply! Here is the genome bin I've been using for my run:
[1.txt](https://github.com/WrightonLabCSU/DRAM/files/8110789/1.txt)

**Comment by rmFlynn** [comment]
Thanks I was able to run the file, but I do have a new version of dram that should be in bioconda, but there is an issue with the bioconda validation pipeline slowing it down. The upgrade should fix it, I think it will be out today.

**Comment by rmFlynn** [comment]
Let me know if I should not close this issue
