### ISSUE TITLE
No descriptions were found for your id's. Does this NP_852561.1 look like an id from viral_description   

### ISSUE THREAD

**Issue by linda5mith** [WrightonLabCSU/DRAM#156]
```
/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this NP_852561.1 look like an id from viral_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],

```
How can I set descriptions for the ID's? 

Command I ran:
`nohup DRAM-v.py annotate -i vs2-pass2/for-dramv/final-viral-combined-for-dramv.fa -v vs2-pass2/for-dramv/viral-affi-contigs-for-dramv.tab -o dramv-annotate2 --skip_trnascan --low_mem_mode --threads 10 --min_contig_size 1000 &`

Full stack trace:
```
/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this NP_852561.1 look like an id from viral_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
2022-03-08 21:45:55.731332: Viral annotation started
0:00:00.239689: Retrieved database locations and descriptions
0:00:00.239739: Annotating final-viral-combined-for-dramv
0:03:55.896743: Turning genes from prodigal to mmseqs2 db
0:03:58.988038: Getting hits from kofam
1:02:59.241979: Getting forward best hits from viral
1:04:23.471563: Getting reverse best hits from viral
1:04:33.207429: Getting descriptions of hits from viral
Traceback (most recent call last):
  File "/home/linda/anaconda3/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 473, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1012, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 920, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 813, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 683, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/home/linda/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]
KeyError: 'NP_852561.1'
```

My config file:

```
DRAM-setup.py print_config
Processed search databases
KEGG db: None
KOfam db: /backup/user_data/linda/DRAM_data/kofam_profiles.hmm
KOfam KO list: /backup/user_data/linda/DRAM_data/kofam_ko_list.tsv
UniRef db: /backup/user_data/linda/DRAM_data/uniref90.20220308.mmsdb
Pfam db: /backup/user_data/linda/DRAM_data/pfam.mmspro
dbCAN db: /backup/user_data/linda/DRAM_data/dbCAN-HMMdb-V10.txt
RefSeq Viral db: /backup/user_data/linda/DRAM_data/refseq_viral.20220308.mmsdb
MEROPS peptidase db: /backup/user_data/linda/DRAM_data/peptidases.20220308.mmsdb
VOGDB db: /backup/user_data/linda/DRAM_data/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: /backup/user_data/linda/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN family activities: /backup/user_data/linda/DRAM_data/CAZyDB.07292021.fam-activities.txt
VOG annotations: /backup/user_data/linda/DRAM_data/vog_annotations_latest.tsv.gz

Description db: /backup/user_data/linda/DRAM_data/description_db.sqlite

DRAM distillation sheets
Genome summary form: /backup/user_data/linda/DRAM_data/genome_summary_form.20220308.tsv
Module step form: /backup/user_data/linda/DRAM_data/module_step_form.20220308.tsv
ETC module database: /backup/user_data/linda/DRAM_data/etc_mdoule_database.20220308.tsv
Function heatmap form: /backup/user_data/linda/DRAM_data/function_heatmap_form.20220308.tsv
AMG database: /backup/user_data/linda/DRAM_data/amg_database.20220308.tsv
```

**Comment by rmFlynn** [comment]
Have you run? `DRAM-setup.py update_description_db` try running that and see if you still get the same error after.

**Comment by linda5mith** [comment]
It worked, thank you!

**Comment by LeoBusse** [comment]
Hello, I've been receiving a similar error on the "No descriptions were found for your id's." I tried the fix above with the update_description_db command, but I am still getting an error when I attempt to run the annotation. 

My script is:
```
module load anaconda/2019.03
conda activate DRAM_Test
DRAM.py annotate -i '/home-3/lbusse2@jhu.edu/G_virus_fa/*.fa' -o gypsum_annotation
```

The error seems to be related to pandas as indicated in the slurm output below, but I'm still new to coding and am not sure exactly how to proceed. 

Thank you in advance!
<img width="1440" alt="Screen Shot 2022-03-13 at 11 36 55 AM" src="https://user-images.githubusercontent.com/70600501/158067548-ff36c675-9bee-4097-9944-c8f1ac6738b6.png">

**Comment by WilkinsLabAdmin** [comment]
Dang I thought this was fixed, what version of dram is this?

**Comment by linda5mith** [comment]
> Dang I thought this was fixed, what version of dram is this?

How can I check?

**Comment by LeoBusse** [comment]
Hello,

I have version 1.3.2

**Comment by linda5mith** [comment]
I have version 1.3.4

**Comment by LeoBusse** [comment]
Hi! I updated to 1.3.4 and ran again but to no avail. I will run the update_description_db command again and let you know. Thank you so much for the help!

<img width="1436" alt="Screen Shot 2022-03-17 at 10 49 56 AM" src="https://user-images.githubusercontent.com/70600501/158830706-7df5c43b-e8e2-40c1-aba4-bf39e5f06556.png">

**Comment by rmFlynn** [comment]
Yes you are now getting a key error and not the int header error from before. I think that once you update descriptions, you will be in a better place.
