### ISSUE TITLE
DRAM.py distill : ValueError: Invalid file path or buffer object type: <class 'NoneType'>

### ISSUE THREAD

**Issue by kalonji08** [WrightonLabCSU/DRAM#165]
Hello I'm having issue running the following code:
DRAM.py distill -i annotation/annotations.tsv -o distill --trna_path annotation/trnas.tsv --rrna_path annotation/rrnas.tsv

Here is the output:

/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:51: UserWarning: Database does not exist at path None
  warnings.warn('Database does not exist at path %s' % self.description_loc)
Traceback (most recent call last):
  File "/home/kalonjilab/miniconda3/envs/DRAM/bin/DRAM.py", line 189, in <module>
    args.func(**args_dict)
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/summarize_genomes.py", line 582, in summarize_genomes
    genome_summary_form = pd.read_csv(database_handler.dram_sheet_locs['genome_summary_form'], sep='\t')
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/pandas/io/common.py", line 670, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/pandas/io/common.py", line 427, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
(DRAM) kalonjilab@kalonjilab-Precision-T7610:/mnt/db1/dram$

**Comment by rmFlynn** [comment]
Sorry I thought I got to this but forgot to hit enter. Did you run `DRAM-setup.py  --update_description_db`?

**Comment by kalonji08** [comment]
@rmFlynn Thank you so much for getting back to me.

Here is the output:
DRAM-setup.py update_description_db
/home/kalonjilab/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:51: UserWarning: Database does not exist at path None
  warnings.warn('Database does not exist at path %s' % self.description_loc)

**Comment by kalonji08** [comment]
@rmFlynn i also run : DRAM-setup.py print_config

And this is what i got:
Processed search databases
KEGG db: None
KOfam db: None
KOfam KO list: None
UniRef db: None
Pfam db: None
dbCAN db: None
RefSeq Viral db: None
MEROPS peptidase db: None
VOGDB db: None

Descriptions of search database entries
Pfam hmm dat: None
dbCAN family activities: None
VOG annotations: None

Description db: None

DRAM distillation sheets
Genome summary form: None
Module step form: None
ETC module database: None
Function heatmap form: None
AMG database: None

Looks like i don't have a DB or i should redo the setup, maybe? How can i do it effectively with 80GB RAM and 32 threads?

**Comment by rmFlynn** [comment]
Hmm where did you set up the database? If the output files are all there, then you can use `DRAM-setup.py set_database_locations `, use `DRAM-setup.py set_database_locations -h` to figure it out. I there is a config file there, it will be named like `CONFIG`, then you can import it with `DRAM-setup.py import_config`

**Comment by kalonji08** [comment]
@rmFlynn the database was set on an second hard drive but it has some superblock issues. I think i will have to replace it and re install evrything follwing the instructions above. Thanks a lot

**Comment by rmFlynn** [comment]
I hope this worked out but given the problem was likely the drive I am going to close this issue.
