### ISSUE TITLE
KeyError when Getting descriptions of hits from viral

### ISSUE THREAD

**Issue by ipetrushin** [WrightonLabCSU/DRAM#167]
Dear DRAM team!

We trying to annotate viral contigs from metagenomic study. Running the DRAM-v.py causes the error related to viral reference database. All databases are prepared following instruction. CONFIG file of mag_annotator contains valid path to viral database.

Running command line:
DRAM-v.py annotate -i RNA_for-dramv/final-viral-combined-for-dramv.fa -v RNA_for -dramv/viral-affi-contigs-for-dramv.tab -o RNA_dramv-annotate --skip_trnascan --threads 16 --min_contig_size 700
Input files [https://disk.yandex.ru/d/bnPqICrJNxNw_Q](url)
```
2022-04-03 11:56:13.195284: Viral annotation started
0:00:00.222380: Retrieved database locations and descriptions
0:00:00.222412: Annotating final-viral-combined-for-dramv
0:00:00.716194: Turning genes from prodigal to mmseqs2 db
0:00:03.719268: Getting hits from kofam

0:04:06.485414: Getting forward best hits from viral
0:04:33.985525: Getting reverse best hits from viral
0:04:56.425342: Getting descriptions of hits from viral
/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this YP_009551462.1 look like an id from viral_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/home/ipetrushin/miniconda3/envs/dram/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 473, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1012, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 920, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 813, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 683, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/home/ipetrushin/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    **header = header_dict[hit]
KeyError: 'YP_009551462.1'**
```
I runned the program multiple times and each time last error is different:
KeyError: 'YP_009336938.1'
KeyError: 'YP_009666352.1'

**Comment by jamesriddellv** [comment]
I am also having this same issue

**Comment by ipetrushin** [comment]
> Check #150 proposed solutions
I think is the same issue as #150 @rmFlynn 
Thanks for the advice about update_description. Running this task on 2Tb node, now it takes 350+ Gb for 11 hours
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1503663 ipetrus+  20   0  361.6g 360.9g  45736 S  17.8  35.8 174:23.49 DRAM-setup.py
```
I really doubt is good idea to store so much data in the SQLite database (25 Gb already and counting)

**Comment by rmFlynn** [comment]
Agreed, I'm looking for a alternatives do you have any ideas?

**Comment by ipetrushin** [comment]
> do you have any ideas?

It depends on data structure and read/write ratio, I don't know the details. For binary storage of objects there are lot of libraries, i.e. https://developers.google.com/protocol-buffers 
If you need structured storage and many read/change requests (SELECT, UPDATE), I prefer standalone DB, i.e. PostgreSQL

**Comment by rmFlynn** [comment]
Thanks, I will take that under consideration!
