### ISSUE TITLE
UserWarning: No descriptions were found for your id's. Does this YP_009966079.1 look like an id from viral_description

### ISSUE THREAD

**Issue by qinjunjun** [WrightonLabCSU/DRAM#183]
Thank you for this useful tool,I met a little bug.
This is my command line:
DRAM-v.py annotate -i final-viral-combined-for-dramv.fa -v viral-affi-contigs-for-dramv.tab -o annotation_out
2022-06-04 18:40:33.748248: Viral annotation started
0:00:00.919200: Retrieved database locations and descriptions
0:00:00.919291: Annotating final-viral-combined-for-dramv
0:04:01.753534: Turning genes from prodigal to mmseqs2 db
0:04:18.797350: Getting hits from kofam
1:36:31.475152: Getting forward best hits from viral
1:37:19.089543: Getting reverse best hits from viral
1:37:29.686614: Getting descriptions of hits from viral
/data1/qinjunjun/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this YP_009966079.1 look like an id from viral_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/data1/qinjunjun/miniconda3/envs/dram/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/data1/qinjunjun/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 475, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/data1/qinjunjun/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1013, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/data1/qinjunjun/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 921, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/data1/qinjunjun/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 814, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/data1/qinjunjun/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 684, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/data1/qinjunjun/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]
KeyError: 'YP_009966079.1'

can you help me? Thank you a lot.

**Comment by rmFlynn** [comment]
This is a reoccurring issue, [example](https://github.com/WrightonLabCSU/DRAM/discussions/178), sometime setup does not finish correctly. This is usually solved by running `DRAM-setup.py update_description_db` let me know if that does not work for you and I will figure out the problem.

**Comment by qinjunjun** [comment]
> This is a reoccurring issue, [example](https://github.com/WrightonLabCSU/DRAM/discussions/178), sometime setup does not finish correctly. This is usually solved by running `DRAM-setup.py update_description_db` let me know if that does not work for you and I will figure out the problem.

Thank you a lot ,now  it works well.

**Comment by rmFlynn** [comment]
Glad to here it!
