### ISSUE TITLE
Trouble with conda installation for distill function

### ISSUE THREAD

**Issue by sophienixon** [WrightonLabCSU/DRAM#190]
Hi there,

I am running DRAM on a number of MAGs and isolate genomes. I am able to annotate ok, but when I try and run the distill function I get the following error:

$DRAM.py distill -i annotations.tsv -o ./Marinobacter_distillate --rrna_path rrnas.tsv --trna_path trnas.tsv
/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:51: UserWarning: Database does not exist at path None
  warnings.warn('Database does not exist at path %s' % self.description_loc)
Traceback (most recent call last):
  File "/home/mbesssn6/.conda/envs/DRAM/bin/DRAM.py", line 189, in <module>
    args.func(**args_dict)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/summarize_genomes.py", line 582, in summarize_genomes
    genome_summary_form = pd.read_csv(database_handler.dram_sheet_locs['genome_summary_form'], sep='\t')
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/pandas/io/common.py", line 670, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/pandas/io/common.py", line 427, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>

This feels like a conda-config issue to me - any ideas on how to fix?

Cheers,
Sophie

**Comment by rmFlynn** [comment]
Can you post the output of `DRAM-setup.py print_config`? or just run `DRAM-setup.py update_dram_forms` and see if it works after that.

**Comment by sophienixon** [comment]
Hi, so I realised after running that that we didn't have databases configured. After fixing an issue with our server regarding FTP access, I hit a wall with the database setup step:

Can not write to data file /mnt/data/DRAM_data/database_files/uniref90.20220729.mmsdb.idx.0
Traceback (most recent call last):
  File "/home/mbesssn6/.conda/envs/DRAM/bin/DRAM-setup.py", line 158, in <module>
    args.func(**args_dict)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 311, in prepare_databases
    output_dbs['uniref_db_loc'] = download_and_process_uniref(uniref_loc, temporary, uniref_version=uniref_version,
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 94, in download_and_process_uniref
    make_mmseqs_db(uniref_fasta_zipped, uniref_mmseqs_db, create_index=True, threads=threads, verbose=verbose)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 38, in make_mmseqs_db
    run_process(['mmseqs', 'createindex', output_loc, tmp_dir, '--threads', str(threads)], verbose=verbose)
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/mbesssn6/.conda/envs/DRAM/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createindex', '/mnt/data/DRAM_data/database_files/uniref90.20220729.mmsdb', '/mnt/data/DRAM_data/database_files/tmp', '--threads', '30']' returned non-zero exit status 1.

Any idea if this is a server or code issue?

**Comment by rmFlynn** [comment]
Try running `mmseqs createindex /mnt/data/DRAM_data/database_files/uniref90.20220729.mmsdb /mnt/data/DRAM_data/database_files/tmp --threads 30` in the same location, I am afraid that dram obviates important command line error messages.
