### ISSUE TITLE
DRAM 1.3.5, using --categories throws key error exception

### ISSUE THREAD

**Issue by gregvonkuster** [WrightonLabCSU/DRAM#194]
For example:
```
$DRAM.py strainer --input_annotations my_annotations.tsv --input_fasta my_fasta.fasta --categories my_category --output_fasta my_output.fasta
Traceback (most recent call last):
  File "~/DRAM.py", line 189, in <module>
    args.func(**args_dict)
  File "~/mag_annotator/pull_sequences.py", line 80, in pull_sequences
    annotation_genes_to_keep = get_genes_from_identifiers(annotations, genes, fastas, scaffolds, identifiers,
  File "~/mag_annotator/pull_sequences.py", line 59, in get_genes_from_identifiers
    genome_summary_form = pd.read_csv(database_handler.db_locs['genome_summary_form'], sep='\t')
KeyError: 'genome_summary_form'
```
I believe the cause / fix is that this line in the code https://github.com/WrightonLabCSU/DRAM, which is currently this:
```
genome_summary_form = pd.read_csv(database_handler.db_locs['genome_summary_form'], sep='\t')
```
should be corrected as shown here:
```
genome_summary_form = pd.read_csv(database_handler.dram_sheet_locs['genome_summary_form'], sep='\t')
```
I've created a PR containing a fix here https://github.com/WrightonLabCSU/DRAM/pull/193

**Comment by rmFlynn** [comment]
Thanks for your contribution!
