### ISSUE TITLE
DRAM.py error message for tRNAscan-SE

### ISSUE THREAD

**Issue by Audra-Leigh** [WrightonLabCSU/DRAM#225]
Hello,

I put the following code in: 
DRAM.py annotate --min_contig_size 1000 --threads 28 -i /fs/ess/PAS1802/Audra/MicEuk_gDNA_optimization/sequencing_run3/augustus/21BE/21BE-1000.fasta -o /fs/ess/PAS1802/Audra/MicEuk_gDNA_optimization/sequencing_run3/DRAM/21BE-annotation

I would also say that I previously ran this on another file and it successful worked and I was able to distill information from the files. 

**I get the following error message:**
Traceback (most recent call last):
  File "/users/PAS1212/osu10462/miniconda3/bin/DRAM.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/users/PAS1212/osu10462/DRAM/scripts/DRAM.py", line 204, in <module>
    args.func(**args_dict)
  File "/users/PAS1212/osu10462/DRAM/mag_annotator/annotate_bins.py", line 1017, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_handler, logger, min_contig_size, prodigal_mode, trans_table,
  File "/users/PAS1212/osu10462/DRAM/mag_annotator/annotate_bins.py", line 910, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, logger, min_contig_size, prodigal_mode, 
  File "/users/PAS1212/osu10462/DRAM/mag_annotator/annotate_bins.py", line 852, in annotate_fasta
    trna_table = run_trna_scan(renamed_scaffolds, tmp_dir, fasta_name, logger, threads=threads, verbose=verbose)
  File "/users/PAS1212/osu10462/DRAM/mag_annotator/annotate_bins.py", line 466, in run_trna_scan
    run_process(['tRNAscan-SE', '-G', '-o', raw_trnas, '--thread', str(threads), fasta], logger, verbose=verbose)
  File "/users/PAS1212/osu10462/DRAM/mag_annotator/utils.py", line 61, in run_process
    results = subprocess.run(command, check=check, shell=shell,
  File "/users/PAS1212/osu10462/miniconda3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/users/PAS1212/osu10462/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/users/PAS1212/osu10462/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tRNAscan-SE'

Thanks 

Audra

**Comment by rmFlynn** [comment]
Is tRNAscan-SE installed? How did you install DRAM?

**Comment by Audra-Leigh** [comment]
I installed DRAM using mamba and so I activate thru mamba activate DRAM. It appears that tRNAscan-SE was not installed so I have installed it manually. That fixed the problem. Thanks!

**Comment by rmFlynn** [comment]
Excellent, I'm always happy for an easy win. I'm closing this but feel free to open it if you have more problems.
