### ISSUE TITLE
DRAM.py annotate stops at "Getting hits from pfam"

### ISSUE THREAD

**Issue by alyzza16** [WrightonLabCSU/DRAM#227]
Hi,

I have been trying to annotate my dataset, but it always stops at "Getting hits from pfam," and I get this error:

> Traceback (most recent call last):
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 475, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1013, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 921, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 829, in annotate_orfs
    annotation_list.append(run_mmseqs_profile_search(query_db, db_handler.db_locs['pfam'], tmp_dir,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 204, in run_mmseqs_profile_search
    run_process(['mmseqs', 'convertalis', query_db, pfam_profile, output_db, output_loc], verbose=verbose)
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'convertalis', 'dramv-annotate-t28/working_dir/final-viral-combined-for-dramv/tmp/gene.mmsdb', '/gxfs_work1/geomar/smomw535/db-dram/pfam.mmspro', 'dramv-annotate-t28/working_dir/final-viral-combined-for-dramv/tmp/pfam.mmsdb', 'dramv-annotate-t28/working_dir/final-viral-combined-for-dramv/tmp/pfam_output.b6']' died with <Signals.SIGABRT: 6>.

I figured it was a memory issue so I increased the memory allocation (I am trying to run this on Slurm). But the error persisted, and still stopped at "Getting hits from pfam."

I created a new conda environment of DRAM with Python v.3.10 (because I have Python v.3.8 installed and I thought maybe that was the issue). It still stopped at "Getting hits from pfam," and this was the error:

> Traceback (most recent call last):
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 475, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1013, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 921, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 829, in annotate_orfs
    annotation_list.append(run_mmseqs_profile_search(query_db, db_handler.db_locs['pfam'], tmp_dir,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 201, in run_mmseqs_profile_search
    run_process(['mmseqs', 'search', query_db, pfam_profile, output_db, tmp_dir, '-k', '5', '-s', '7', '--threads',
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/lib/python3.10/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/gxfs_home/geomar/smomw535/miniconda3/envs/DRAM-py3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'search', 'dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/gene.mmsdb', '/gxfs_work1/geomar/smomw535/db-dram/pfam.mmspro', 'dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/pfam.mmsdb', 'dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/tmp', '-k', '5', '-s', '7', '--threads', '28']' returned non-zero exit status 1.

I'm stuck and do not know what to try next.

**Comment by rmFlynn** [comment]
try reducing the number of threads mmseqs uses less memory when you have fewer threads. you can also just run `mmseqs search dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/gene.mmsdb /gxfs_work1/geomar/smomw535/db-dram/pfam.mmspro dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/pfam.mmsdb dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/tmp -k 5 -s 7 --threads 28` see if that runs on its own.

**Comment by rmFlynn** [comment]
There may be a problem with the latest version of pfam I am looking into it

**Comment by alyzza16** [comment]
> try reducing the number of threads mmseqs uses less memory when you have fewer threads. you can also just run `mmseqs search dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/gene.mmsdb /gxfs_work1/geomar/smomw535/db-dram/pfam.mmspro dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/pfam.mmsdb dramv-annotate-update-dram/working_dir/final-viral-combined-for-dramv/tmp/tmp -k 5 -s 7 --threads 28` see if that runs on its own.

I tried running mmseqs search on its own and it worked! Also redid the whole annotation step and it finished in 6 hours. Thank you for your help!

**Comment by rmFlynn** [comment]
I will push an upgrade once I have it figured out myself.

**Comment by rmFlynn** [comment]
Run this to fix for now, looking into the problem before I push `conda install mmseqs2==13.45111`
