### ISSUE TITLE
DRAM-setup.py set_database_locations issue

### ISSUE THREAD

**Issue by dgittins** [WrightonLabCSU/DRAM#240]
Hello

I installed DRAM (v 1.4.1) using miniconda and imported existing databases using `DRAM-setup.py import_config --config_loc  my_old_config.txt`. 

Two of the databases (kofam_profiles.hmm and Pfam-A.hmm.dat.gz) were not found, so I tried `DRAM-setup.py set_database_locations --kofam_hmm_loc /work/ebg_lab/referenceDatabases/DRAM2/kofam_profiles.hmm --pfam_hmm_loc /work/ebg_lab/referenceDatabases/DRAM2/Pfam-A.hmm.dat.gz --update_description_db` to add them. However, I got the following error:

```
2022-12-08 16:42:12,932 - Logging to console
Traceback (most recent call last):
  File "/home/daniel.gittins/miniconda3/envs/dram/bin/DRAM-setup.py", line 184, in <module>
    args.func(**args_dict)
  File "/home/daniel.gittins/miniconda3/envs/dram/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 434, in set_database_paths
    db_handler.set_database_paths(**kargs, write_config=True)
TypeError: DatabaseHandler.set_database_paths() got an unexpected keyword argument 'dbcan_fam_activities'
```

Do you know what is causing this issue?

For reference, the output of `DRAM-setup.py print_config`:

```
2022-12-09 08:26:36,326 - Logging to console
Processed search databases
KEGG db: None
KOfam db: None
KOfam KO list: /work/ebg_lab/referenceDatabases/DRAM2/kofam_ko_list.tsv
UniRef db: /work/ebg_lab/referenceDatabases/DRAM2/uniref90.20220122.mmsdb
Pfam db: /work/ebg_lab/referenceDatabases/DRAM2/pfam.mmspro
dbCAN db: /work/ebg_lab/referenceDatabases/DRAM2/dbCAN-HMMdb-V9.txt
RefSeq Viral db: /work/ebg_lab/referenceDatabases/DRAM2/refseq_viral.20220122.mmsdb
MEROPS peptidase db: /work/ebg_lab/referenceDatabases/DRAM2/peptidases.20220122.mmsdb
VOGDB db: /work/ebg_lab/referenceDatabases/DRAM2/vog_latest_hmms.txt
Descriptions of search database entries
Pfam hmm dat: None
dbCAN family activities: /work/ebg_lab/referenceDatabases/DRAM2/CAZyDB.07302020.fam-activities.txt
VOG annotations: /work/ebg_lab/referenceDatabases/DRAM2/vog_annotations_latest.tsv.gz

Description db: /work/ebg_lab/referenceDatabases/DRAM2/description_db.sqlite

DRAM distillation sheets
Genome summary form: /work/ebg_lab/referenceDatabases/DRAM2/genome_summary_form.20220122.tsv
Module step form: /work/ebg_lab/referenceDatabases/DRAM2/module_step_form.20220122.tsv
ETC module database: /work/ebg_lab/referenceDatabases/DRAM2/etc_mdoule_database.20220122.tsv
Function heatmap form: /work/ebg_lab/referenceDatabases/DRAM2/function_heatmap_form.20220122.tsv
AMG database: /work/ebg_lab/referenceDatabases/DRAM2/amg_database.20220122.tsv
```

Thank you

**Comment by rmFlynn** [comment]
Yes I do, this is a true bug and I do apologize. I will have it fixed in a moment.

**Comment by rmFlynn** [comment]
The fix should make its way into bioconda within 24h. In the meantime you can use export_config and import_config, both in DRAM-setup.py, to export the config file, edit it and import it again.

**Comment by dgittins** [comment]
Thank you Rory.

The config file (produced using `DRAM-setup.py export_config --output_file old.config`) has paths for kofam_profiles.hmm and Pfam-A.hmm.dat.gz, but these are not found with `DRAM-setup.py print_config`.

Output of `DRAM-setup.py export_config --output_file old.config`:

```
{
  "search_databases": {
    "kegg": null,
    "kofam": "/work/ebg_lab/referenceDatabases/DRAM2/kofam_profiles.hmm",
    "kofam_ko_list": "/work/ebg_lab/referenceDatabases/DRAM2/kofam_ko_list.tsv",
    "uniref": "/work/ebg_lab/referenceDatabases/DRAM2/uniref90.20220122.mmsdb",
    "pfam": "/work/ebg_lab/referenceDatabases/DRAM2/pfam.mmspro",
    "dbcan": "/work/ebg_lab/referenceDatabases/DRAM2/dbCAN-HMMdb-V9.txt",
    "viral": "/work/ebg_lab/referenceDatabases/DRAM2/refseq_viral.20220122.mmsdb",
    "peptidase": "/work/ebg_lab/referenceDatabases/DRAM2/peptidases.20220122.mmsdb",
    "vogdb": "/work/ebg_lab/referenceDatabases/DRAM2/vog_latest_hmms.txt",
    "pfam_hmm_dat": "/work/ebg_lab/referenceDatabases/DRAM2/Pfam-A.hmm.dat.gz"
  },
  "database_descriptions": {
    "dbcan_fam_activities": "/work/ebg_lab/referenceDatabases/DRAM2/CAZyDB.07302020.fam-activities.txt",
    "vog_annotations": "/work/ebg_lab/referenceDatabases/DRAM2/vog_annotations_latest.tsv.gz"
  },
  "dram_sheets": {
    "genome_summary_form": "/work/ebg_lab/referenceDatabases/DRAM2/genome_summary_form.20220122.tsv",
    "module_step_form": "/work/ebg_lab/referenceDatabases/DRAM2/module_step_form.20220122.tsv",
    "etc_module_database": "/work/ebg_lab/referenceDatabases/DRAM2/etc_mdoule_database.20220122.tsv",
    "function_heatmap_form": "/work/ebg_lab/referenceDatabases/DRAM2/function_heatmap_form.20220122.tsv",
    "amg_database": "/work/ebg_lab/referenceDatabases/DRAM2/amg_database.20220122.tsv"
  },
  "dram_version": "1.4.1",
  "description_db": "/work/ebg_lab/referenceDatabases/DRAM2/description_db.sqlite",
  "setup_info": {},
  "log_path": null
}
```

Output of `DRAM-setup.py print_config`:

```
2022-12-13 09:52:41,485 - Logging to console
Processed search databases
KEGG db: None
KOfam db: None
KOfam KO list: /work/ebg_lab/referenceDatabases/DRAM2/kofam_ko_list.tsv
UniRef db: /work/ebg_lab/referenceDatabases/DRAM2/uniref90.20220122.mmsdb
Pfam db: /work/ebg_lab/referenceDatabases/DRAM2/pfam.mmspro
dbCAN db: /work/ebg_lab/referenceDatabases/DRAM2/dbCAN-HMMdb-V9.txt
RefSeq Viral db: /work/ebg_lab/referenceDatabases/DRAM2/refseq_viral.20220122.mmsdb
MEROPS peptidase db: /work/ebg_lab/referenceDatabases/DRAM2/peptidases.20220122.mmsdb
VOGDB db: /work/ebg_lab/referenceDatabases/DRAM2/vog_latest_hmms.txt
Descriptions of search database entries
Pfam hmm dat: None
dbCAN family activities: /work/ebg_lab/referenceDatabases/DRAM2/CAZyDB.07302020.fam-activities.txt
VOG annotations: /work/ebg_lab/referenceDatabases/DRAM2/vog_annotations_latest.tsv.gz

Description db: /work/ebg_lab/referenceDatabases/DRAM2/description_db.sqlite

DRAM distillation sheets
Genome summary form: /work/ebg_lab/referenceDatabases/DRAM2/genome_summary_form.20220122.tsv
Module step form: /work/ebg_lab/referenceDatabases/DRAM2/module_step_form.20220122.tsv
ETC module database: /work/ebg_lab/referenceDatabases/DRAM2/etc_mdoule_database.20220122.tsv
Function heatmap form: /work/ebg_lab/referenceDatabases/DRAM2/function_heatmap_form.20220122.tsv
AMG database: /work/ebg_lab/referenceDatabases/DRAM2/amg_database.20220122.tsv
```


I'll try `DRAM-setup.py set_database_locations` again when the fix is in bioconda (no update just yet).

**Comment by rmFlynn** [comment]
Replace, the config with this:

```
 {
  "search_databases": {
    "kegg": null,
    "kofam_hmm": "/work/ebg_lab/referenceDatabases/DRAM2/kofam_profiles.hmm",
    "kofam_ko_list": "/work/ebg_lab/referenceDatabases/DRAM2/kofam_ko_list.tsv",
    "uniref": "/work/ebg_lab/referenceDatabases/DRAM2/uniref90.20220122.mmsdb",
    "pfam": "/work/ebg_lab/referenceDatabases/DRAM2/pfam.mmspro",
    "dbcan": "/work/ebg_lab/referenceDatabases/DRAM2/dbCAN-HMMdb-V9.txt",
    "viral": "/work/ebg_lab/referenceDatabases/DRAM2/refseq_viral.20220122.mmsdb",
    "peptidase": "/work/ebg_lab/referenceDatabases/DRAM2/peptidases.20220122.mmsdb",
    "vogdb": "/work/ebg_lab/referenceDatabases/DRAM2/vog_latest_hmms.txt"

  },
  "database_descriptions": {
    "dbcan_fam_activities": "/work/ebg_lab/referenceDatabases/DRAM2/CAZyDB.07302020.fam-activities.txt",
    "vog_annotations": "/work/ebg_lab/referenceDatabases/DRAM2/vog_annotations_latest.tsv.gz",
    "pfam_hmm_dat": "/work/ebg_lab/referenceDatabases/DRAM2/Pfam-A.hmm.dat.gz"
  },
  "dram_sheets": {
    "genome_summary_form": "/work/ebg_lab/referenceDatabases/DRAM2/genome_summary_form.20220122.tsv",
    "module_step_form": "/work/ebg_lab/referenceDatabases/DRAM2/module_step_form.20220122.tsv",
    "etc_module_database": "/work/ebg_lab/referenceDatabases/DRAM2/etc_mdoule_database.20220122.tsv",
    "function_heatmap_form": "/work/ebg_lab/referenceDatabases/DRAM2/function_heatmap_form.20220122.tsv",
    "amg_database": "/work/ebg_lab/referenceDatabases/DRAM2/amg_database.20220122.tsv"
  },
  "dram_version": "1.4.1",
  "description_db": "/work/ebg_lab/referenceDatabases/DRAM2/description_db.sqlite",
  "setup_info": {},
  "log_path": null
}
```

**Comment by rmFlynn** [comment]
IDK if this happened because the config was old or if this just was not captured in my tests, but I will find out.

**Comment by rmFlynn** [comment]
Sometimes conda gets hung-up I will look into that too

**Comment by dgittins** [comment]
Thanks Rory.

Updating DRAM to version 1.4.3 and running `DRAM-setup.py import_config --config_loc old.config` using the following config worked:

```
{
  "search_databases": {
    "kegg": null,
    "kofam_ko_list": "/work/ebg_lab/referenceDatabases/DRAM2/kofam_ko_list.tsv",
    "uniref": "/work/ebg_lab/referenceDatabases/DRAM2/uniref90.20220122.mmsdb",
    "pfam": "/work/ebg_lab/referenceDatabases/DRAM2/pfam.mmspro",
    "dbcan": "/work/ebg_lab/referenceDatabases/DRAM2/dbCAN-HMMdb-V9.txt",
    "viral": "/work/ebg_lab/referenceDatabases/DRAM2/refseq_viral.20220122.mmsdb",
    "peptidase": "/work/ebg_lab/referenceDatabases/DRAM2/peptidases.20220122.mmsdb",
    "vogdb": "/work/ebg_lab/referenceDatabases/DRAM2/vog_latest_hmms.txt",
    "kofam_hmm": "/work/ebg_lab/referenceDatabases/DRAM2/kofam_profiles.hmm"
  },
  "database_descriptions": {
    "dbcan_fam_activities": "/work/ebg_lab/referenceDatabases/DRAM2/CAZyDB.07302020.fam-activities.txt",
    "vog_annotations": "/work/ebg_lab/referenceDatabases/DRAM2/vog_annotations_latest.tsv.gz",
    "pfam_hmm": "/work/ebg_lab/referenceDatabases/DRAM2/Pfam-A.hmm.dat.gz"
  },
  "dram_sheets": {
    "genome_summary_form": "/work/ebg_lab/referenceDatabases/DRAM2/genome_summary_form.20220122.tsv",
    "module_step_form": "/work/ebg_lab/referenceDatabases/DRAM2/module_step_form.20220122.tsv",
    "etc_module_database": "/work/ebg_lab/referenceDatabases/DRAM2/etc_mdoule_database.20220122.tsv",
    "function_heatmap_form": "/work/ebg_lab/referenceDatabases/DRAM2/function_heatmap_form.20220122.tsv",
    "amg_database": "/work/ebg_lab/referenceDatabases/DRAM2/amg_database.20220122.tsv"
  },
  "dram_version": "1.4.3",
  "description_db": "/work/ebg_lab/referenceDatabases/DRAM2/description_db.sqlite",
  "setup_info": {},
  "log_path": null
}
```

Thanks for all your help with this! I look forward to using DRAM.

**Comment by rmFlynn** [comment]
I will close this issue for now, As this problem should be solved. In perpetuity.
