### ISSUE TITLE
DRAM-setup.py prepare_databases issue

### ISSUE THREAD

**Issue by YilingWang1997** [WrightonLabCSU/DRAM#242]
Hello

I installed DRAM using miniconda and tried to download databases. However, I got the following error:

`2022-12-14 14:45:34,409 - dbCAN database processed
2022-12-14 14:45:34,411 - Moved dbcan to final destination, configuration updated
2022-12-14 14:45:34,413 - Moved dbcan_fam_activities to final destination, configuration updated
2022-12-14 14:45:34,415 - Moved dbcan_subfam_ec to final destination, configuration updated
2022-12-14 14:45:34,417 - Moved vog_annotations to final destination, configuration updated
2022-12-14 14:45:34,417 - Processing viral
2022-12-14 14:45:41,871 - RefSeq viral database processed
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 184, in <module>
    args.func(**args_dict)
  File "/home/ec2-user/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 619, in prepare_databases
    db_handler.set_database_paths(**{f"{k}_loc":v})
TypeError: DatabaseHandler.set_database_paths() got an unexpected keyword argument 'viral_loc'`

Do you know how to solve this problem?
Thank you!

**Comment by rmFlynn** [comment]
For you, I would install dram_bio 1.4.0 I introduced a bug in 1.4.2 trying to fix a bug in 1.4.0 I am fixing it now but 1.4.0 bug will not stop you in your case. `conda install -c bioconda dram==1.4.0`

**Comment by rmFlynn** [comment]
All bugs seem to be corrected for this issue
