### ISSUE TITLE
Regarding Viral AMG classification

### ISSUE THREAD

**Issue by ShailNair** [WrightonLabCSU/DRAM#251]
Hi,  and many thanks for the excellent annotation tool. I have a query regarding viral AMG annotation. I have a bunch of viral contigs identified through metagenomics. The contigs were cleaned using Checkv and prepared for DRAM-V using virsorter2.
I found some of the probable AMGs in the main annotation.tsv (not distilled) with virsorter category score of 0-2, and an auxiliary score less than 4, but without any AMG flags. I understand that the lack of AMG flag may be the reason they were not included in the final distillate due to the limitations of the AMG database used by DRAMV. 
l also looked for viral-like genes in these contigs using the [pVOGs](https://academic.oup.com/nar/article/45/D1/D491/2333930), [RefSeq-viral](https://www.ncbi.nlm.nih.gov/refseq/), and [ PHROGS](https://phrogs.lmge.uca.fr/index.php) databases with an e-value cutoff of <1E-5.  However, I am still unsure whether these genes should be classified as AMGs or not, as some of them appear to meet the criteria for [AMG classifications](https://github.com/WrightonLabCSU/DRAM/wiki/1.-How-DRAM-Works#dram-v-in-detail) except the missing AMG flag. Here is my annotated  figure:

![eps gene cluster](https://user-images.githubusercontent.com/59241611/211187803-d9c32a07-53c5-4e53-94d8-75440421a0dd.jpg)

Would be happy to know others' insights. I am mostly interested to know what if a virus contig contains a gene cluster (participating in one function) of more than three genes as in the case of **contig A** in the above picture. Here, the **contig A** has a size of more than 150 kb (which falls into the jumbo phage category), is complete, and is without contamination (checkV criteria).

**Comment by rmFlynn** [comment]
Very interesting, I will assign this to our viral team. But first, here are some quick thoughts:

- Remember that some flags make a gene not an amg, I would be interested in the raw data on genes with no flags in this case.
-  We use a minimum cut off of e-15.
- Some databases use hmmer and some use mmseqs, this can affect the end matches and thus the flags.
- Using kegg vs kofam will have an effect here also. 
-  you can vew the amg_database in the [data section](https://github.com/WrightonLabCSU/DRAM/tree/master/data) of this GitHub repo and that would tell you more. 
- Finally, we have actually updated the amg summary so recently that it has not hit the conda repository yet so you may want to rerun in a week or so. 

Do consider sharing your data if you are able this will make DRAM stronger.
These are just some quick notes you may want to mull over if you have not already expect a longer discussion in the future.

**Comment by ShailNair** [comment]
Hi, thank you for the prompt reply. Yes, I did check the AMG database, and the AMGs I am focussed on are not included there.  I have attached the raw files and the dramV annotations of the probable AMGS here. 
 For your reference, I've also provided additional genes (genes before and after the likely AMG), although my question only pertains to genes with the following kegg orthologs (KO):
K16566
K16557
K16554
K16556
K16558
K16555
K16568
K16564
K16560
K16563
All of which are involved in the Exopolysaccharide biosynthesis process.

Thank you 
[dramv.output.zip](https://github.com/WrightonLabCSU/DRAM/files/10372320/dramv.output.zip)

**Comment by rmFlynn** [comment]
Thanks!  We will look to add them to AMG database. If you want to add them your self and do a pull request, then you can get the credit on GitHub for your work and can say you are a contributor to DRAM. But I would understand if you wanted to wait until we confirm these to do so. Of course, we will also look into more broad ways to improve the amg database also.

**Comment by ShailNair** [comment]
I'll wait because I have to conduct a deeper analysis to be confident that these are potential AMGs. Also, it is worthwhile to hear from you, once you have explored the provided files.
Thank you for everything you and your team are doing with DRAM.

**Comment by ShailNair** [comment]
@rmFlynn Hi, any update regarding this issue? Would love to get your input.

**Comment by Xuyang-Feng** [comment]
@ShailNair Hi, I am a beginner of DRAM-V. Could you tell me how big is your description_db.sqlite. My description_db.sqlite is only 330M. Since my DRAM-V annotation step always went wrong, I want to know whether it is the correct size. Thank you very much.

**Comment by ShailNair** [comment]
@Xuyang-Feng Where is the description_db.sqlite located? . You said your DRAM-V process encountered an error. Perhaps post the error and log in the issue section so the authors can help you. Did you check if a similar issue has been resolved earlier?

**Comment by Xuyang-Feng** [comment]
> @Xuyang-Feng Where is the description_db.sqlite located? . You said your DRAM-V process encountered an error. Perhaps post the error and log in the issue section so the authors can help you. Did you check if a similar issue has been resolved earlier?

@ShailNair My description_db.sqlite located in the DRAM_data, which was set in this command `DRAM-setup.py prepare_databases --output_dir DRAM_data`.  The problem I met is that
 '2024-11-20 11:37:51,452 - Retrieved database locations and descriptions
2024-11-20 11:37:51,452 - Annotating final-viral-combined-for-dramv
2024-11-20 15:20:38,053 - Turning genes from prodigal to mmseqs2 db
2024-11-20 15:21:41,885 - Getting hits from kofam
2024-11-22 12:38:22,361 - One of your requested annotation databases is missing. If you did not specify KEGG database, distillate will be of limited use. If no CAMPER source was provided (as of DRAM v1.5.0, it is still not automa
tically included), and you want to annotate with CAMPER - see instructions on GitHub for downloading if you would like to run t
his tool as a standalone: https://github.com/WrightonLabCSU/CAMPER.
2024-11-22 12:38:22,363 - Getting forward best hits from viral
2024-11-22 14:10:01,269 - Getting reverse best hits from viral
2024-11-22 14:15:48,148 - Getting descriptions of hits from viral
2024-11-22 14:23:51,852 - Getting forward best hits from peptidase
2024-11-22 15:29:27,742 - Getting reverse best hits from peptidase
2024-11-22 15:29:43,390 - Getting descriptions of hits from peptidase
2024-11-22 15:30:08,104 - Getting hits from pfam
2024-11-22 15:57:14,155 - Getting hits from dbCAN
/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_handler.py:235: UserWarning: No descriptions were found for your id's. Does this SLH look like an id from dbcan_description
  warnings.warn(
/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_handler.py:235: UserWarning: No descriptions were found for your id's. Does this SLH look like an id from dbcan_description
  warnings.warn(
/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_handler.py:235: UserWarning: No descriptions were found for your id's. Does this GT2_Glycos_transf_2 look like an id from dbcan_description
  warnings.warn(
/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_handler.py:235: UserWarning: No descriptions were found for your id's. Does this GT2_Glyco_tranf_2_3 look like an id from dbcan_description
  warnings.warn(
/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_handler.py:235: UserWarning: No descriptions were found for your id's. Does this PL10_2 look like an id from dbcan_description
  warnings.warn(
/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_handler.py:235: UserWarning: No descriptions were found for your id's. Does this GH43_23 look like an id from dbcan_description
  warnings.warn(
/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_handler.py:235: UserWarning: No descriptions were found for your id's. Does this GH19_1 look like an id from dbcan_description
  warnings.warn(
2024-11-22 17:03:57,879 - Getting hits from VOGDB
2024-11-26 06:46:50,170 - Merging ORF annotations
2024-11-26 10:50:03,910 - Interval added to gff started less than zero, set to zero
Traceback (most recent call last):
  File "/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/bin/DRAM-v.py", line 161, in <module>
    args.func(**args_dict)
  File "/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 485, in annotate_vgfs
    annotations = annotate_fastas(
  File "/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1410, in annotate_fastas
    annotate_fasta(
  File "/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1336, in annotate_fasta
    make_gbk_from_gff_and_fasta(
  File "/hwfshrb1/B2C_ZH1/yangfangming/.conda/envs/dram_env/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 604, in make_gbk_from_gff_and_fasta
    io.StringIO(concat_gff), format="gff3", into=Sequence, seq_num=i
MemoryError.'   I am not sure whether my description_db.sqlite is correct, since I find other's description_db.sqlite is much bigger than me. Thank you for your kind reply.

**Comment by Xuyang-Feng** [comment]
@ShailNair Thank you for your reply. I will try to test the program by running it on a single viral contig.
