### ISSUE TITLE
Issue in database setup 

### ISSUE THREAD

**Issue by del-oxyribonucleic-acid** [WrightonLabCSU/DRAM#264]
Hello!
I am having issues downloading all the databases to setup DRAM. Here is the command I used: 

(DRAM) delaney@ada:~/software/DRAM$ ./DRAM-setup.py prepare_databases --output_dir DRAM_data

and here is the error: 

`2023-02-16 22:16:17.565696: Database preparation started
Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V10/CAZyDB.07292021.fam-activities.txt
Downloading dbCAN from: http://bcb.unl.edu/dbCAN2/download/dbCAN-HMMdb-V10.txt
0:00:08.148141: dbCAN database processed
10:15:04.073746: UniRef database processed
12:08:25.002664: PFAM database processed
Traceback (most recent call last):
  File "/home/delaney/software/DRAM/./DRAM-setup.py", line 158, in <module>
    args.func(**args_dict)
  File "/home/delaney/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 317, in prepare_databases
    output_dbs['viral_db_loc'] = download_and_process_viral_refseq(viral_loc, temporary, threads=threads,
  File "/home/delaney/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 163, in download_and_process_viral_refseq
    download_file(refseq_url, refseq_faa, verbose=verbose)
  File "/home/delaney/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 16, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/home/delaney/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/delaney/miniconda3/envs/DRAM/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'DRAM_data/database_files/viral.2.protein.faa.gz', 'ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.2.protein.faa.gz']' returned non-zero exit status 8.
`

Any help would be greatly appreciated!

**Comment by del-oxyribonucleic-acid** [comment]
I tried to reinstall DRAM and now am getting a different issue:

`(DRAM) delaney@ada:~/software/DRAM$ ./DRAM-setup.py prepare_databases --output_dir DRAM_data
Traceback (most recent call last):
  File "/home/delaney/software/DRAM/./DRAM-setup.py", line 158, in <module>
    args.func(**args_dict)
TypeError: prepare_databases() got an unexpected keyword argument 'pfam_hmm_dat'`

**Comment by anbadilla** [comment]
I am having the same issue as in your original post. 
How did you get it solved?

Log:

```
2024-04-08 13:26:12.889888: Database preparation started
Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V10/CAZyDB.07292021.fam-activities.txt
downloading https://bcb.unl.edu/dbCAN2/download/Databases/V10/CAZyDB.07292021.fam-activities.txt
downloading ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.dat.gz
Downloading dbCAN from: http://bcb.unl.edu/dbCAN2/download/dbCAN-HMMdb-V10.txt
downloading http://bcb.unl.edu/dbCAN2/download/dbCAN-HMMdb-V10.txt
0:00:07.568297: dbCAN database processed
downloading ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz
2:17:42.226771: PFAM database processed
downloading ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.protein.faa.gz
downloading ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.2.protein.faa.gz
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/a/abadilla/.conda/envs/WGS/bin/DRAM-setup.py", line 158, in <module>
    args.func(**args_dict)
  File "/afs/crc.nd.edu/user/a/abadilla/.conda/envs/WGS/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 317, in prepare_databases
    output_dbs['viral_db_loc'] = download_and_process_viral_refseq(viral_loc, temporary, threads=threads,
  File "/afs/crc.nd.edu/user/a/abadilla/.conda/envs/WGS/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 163, in download_and_process_viral_refseq
    download_file(refseq_url, refseq_faa, verbose=verbose)
  File "/afs/crc.nd.edu/user/a/abadilla/.conda/envs/WGS/lib/python3.8/site-packages/mag_annotator/utils.py", line 16, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/afs/crc.nd.edu/user/a/abadilla/.conda/envs/WGS/lib/python3.8/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/afs/crc.nd.edu/user/a/abadilla/.conda/envs/WGS/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'dram_db/database_files/viral.2.protein.faa.gz', 'ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.2.protein.faa.gz']' returned non-zero exit status 8.


```

Thanks,
Andrei
