### ISSUE TITLE
KeyError: 'amg_database' in DRAM-v

### ISSUE THREAD

**Issue by nologo68** [WrightonLabCSU/DRAM#289]
I was running DRAM-v to annotate some VirSorter2 results before distillation, but in the error file I got this:

/mnt/home/soft/dramv/programs/x86_64/1.4.6/lib/python3.9/site-packages/mag_annotator/database_handler.py:123: UserWarning: Database does not exist at path None
  warnings.warn("Database does not exist at path %s" % description_loc)
/mnt/home/soft/dramv/programs/x86_64/1.4.6/lib/python3.9/site-packages/mag_annotator/database_handler.py:537: UserWarning: Sequences will not be annoated against VOGDB as it is not configured for use in DRAM
  warnings.warn(
2023-07-27 11:36:12,402 - 1 fastas found
2023-07-27 11:36:12,403 - Checking for duplicate names
2023-07-27 11:36:12,623 - No duplicate names found
2023-07-27 11:36:12,624 - Starting the Viral Annotation of Genes with database configuration:

2023-07-27 11:36:12,627 - Retrieved database locations and descriptions
2023-07-27 11:36:12,627 - Annotating final-viral-combined-for-dramv
2023-07-27 11:48:20,796 - Turning genes from prodigal to mmseqs2 db
2023-07-27 11:48:25,234 - No KEGG source provided so distillation will be of limited use.
2023-07-27 11:48:33,287 - Merging ORF annotations
2023-07-27 16:02:27,738 - Annotations complete, processing annotations
Traceback (most recent call last):
  File "/mnt/home/soft/dramv/programs/x86_64/1.4.6/bin/DRAM-v.py", line 161, in <module>
    args.func(**args_dict)
  File "/mnt/home/soft/dramv/programs/x86_64/1.4.6/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 507, in annotate_vgfs
    annotations = add_dramv_scores_and_flags(annotations, db_handler, logger, virsorter_hits, input_fasta)
  File "/mnt/home/soft/dramv/programs/x86_64/1.4.6/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 385, in add_dramv_scores_and_flags
    amg_database_frame = pd.read_csv(db_handler.config['dram_sheets']['amg_database'], sep='\t')
KeyError: 'amg_database'

**Comment by TJrogers86** [comment]
Did you ever figure out this issue?

**Comment by alexandra-valeanu** [comment]
@nologo68 , @TJrogers86 did you manage to solve this error?
