### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by mw55309** [WrightonLabCSU/DRAM#312]
Just after completing the metabolism summary:

```sh
2023-11-05 15:44:07,631 - Generated genome metabolism summary
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/DRAM/bin/DRAM.py", line 207, in <module>
    args.func(**args_dict)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/summarize_genomes.py", line 720, in summarize_genomes
    liquor.save(path.join(output_dir, 'product_%s.html' % i))
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/vegalite/v4/api.py", line 488, in save
    result = save(**kwds)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/save.py", line 83, in save
    spec = chart.to_dict()
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/vegalite/v4/api.py", line 384, in to_dict
    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 326, in to_dict
    result = _todict(
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 60, in _todict
    return {
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 61, in <dictcomp>
    k: _todict(v, validate, context)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 58, in _todict
    return [_todict(v, validate, context) for v in obj]
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 58, in <listcomp>
    return [_todict(v, validate, context) for v in obj]
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 56, in _todict
    return obj.to_dict(validate=validate, context=context)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/vegalite/v4/api.py", line 384, in to_dict
    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 326, in to_dict
    result = _todict(
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 60, in _todict
    return {
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 61, in <dictcomp>
    k: _todict(v, validate, context)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 58, in _todict
    return [_todict(v, validate, context) for v in obj]
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 58, in <listcomp>
    return [_todict(v, validate, context) for v in obj]
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/schemapi.py", line 56, in _todict
    return obj.to_dict(validate=validate, context=context)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/vegalite/v4/api.py", line 2020, in to_dict
    return super().to_dict(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/vegalite/v4/api.py", line 374, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/vegalite/v4/api.py", line 89, in _prepare_data
    data = _pipe(data, data_transformers.get())
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/vegalite/data.py", line 19, in default_data_transformer
    return curried.pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/data.py", line 149, in to_values
    data = sanitize_dataframe(data)
  File "/home/ubuntu/miniconda3/envs/DRAM/lib/python3.10/site-packages/altair/utils/core.py", line 317, in sanitize_dataframe
    for col_name, dtype in df.dtypes.iteritems():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'iteritems'
```

Looks like a pandas version issue? Perhaps? But I am using the DRAM conda environment, so that shouldn't happen?

**Comment by mw55309** [comment]
Closing this - DRAM was picking up other versions of PANDAS installed outside of the env.
Had to remove all of those.
