### ISSUE TITLE
Problem with DRAM databases installation

### ISSUE THREAD

**Issue by apazminov** [WrightonLabCSU/DRAM#322]
Hello,

I am having some issues with the database installation process. I was using the following command: DRAM-setup.py prepare_databases --output_dir DRAM_data.

The process was going well, but I got this error: 
Processing uniref
2023-12-17 09:16:39,817 - The subcommand ['mmseqs', 'createindex', 'DRAM_data/uniref90.20231217.mmsdb', 'DRAM_data/tmp', '--threads', '10'] experienced an error: Could not create symlink of DRAM_data/tmp/18059588701634138799!
Traceback (most recent call last):
  File "/home/biotechlab/anaconda3/envs/DRAM/bin/DRAM-setup.py", line 184, in <module>
    args.func(**args_dict)
  File "/home/biotechlab/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 555, in prepare_databases
    processed_locs = process_functions[i](locs[i], output_dir, LOGGER,
  File "/home/biotechlab/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 262, in process_uniref
    make_mmseqs_db(uniref_fasta_zipped, uniref_mmseqs_db, logger, create_index=True, threads=threads, verbose=verbose)
  File "/home/biotechlab/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 98, in make_mmseqs_db
    run_process(['mmseqs', 'createindex', output_loc, tmp_dir, '--threads', str(threads)], logger, verbose=verbose)
  File "/home/biotechlab/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 71, in run_process
    raise subprocess.SubprocessError(f"The subcommand {' '.join(command)} experienced an error, see the log for more info.")
subprocess.SubprocessError: The subcommand mmseqs createindex DRAM_data/uniref90.20231217.mmsdb DRAM_data/tmp --threads 10 experienced an error, see the log for more info.

It seems it could be related to an issue with some of the scripts used during this process, as the log file gives no further information. 

I am using dram 1.4.6

Please if you could look into this issue, it would be much appreciated.

Thank you very much,
Miguel

**Comment by SwapnilDoijad** [comment]
I also have the same error; any update?
