### ISSUE TITLE
DRAM 1.5.0 installation issues

### ISSUE THREAD

**Issue by karenhn** [WrightonLabCSU/DRAM#330]
Hi, I've recently installed DRAM 1.5.0. using 

`wget https://raw.githubusercontent.com/WrightonLabCSU/DRAM/master/environment.yaml`
`conda env create -f environment.yaml -n DRAM`

When I started `DRAM-setup.py prepare_databases --output_dir DRAM_data --uniref_loc uniref90.fasta.gz ` 

I had this error:
`File "/home/karenhn/.conda/envs/DRAM/bin/DRAM-setup.py", line 124
    set_db_locs_parser.add_argument('--camper_tar_gz_loc', default=None,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?`
I found in the script for DRAM-setup.py there's two lines which have been transposed [there are two help=mmseqs2... lines following each other, and one should be after the --viral_loc line].  Once I fixed that, I ran the script again but got a different error:

`Traceback (most recent call last):
  File "/home/karenhn/.conda/envs/DRAM/bin/DRAM-setup.py", line 187, in <module>
    args.func(**args_dict)
  File "/home/karenhn/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 5 31, in prepare_databases
    db_handler = DatabaseHandler(logger=LOGGER)
  File "/home/karenhn/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 77,  in __init__
    self.load_config(config_loc)
  File "/home/karenhn/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 82,  in load_config
    conf = json.loads(open(config_file).read())
  File "/home/karenhn/.conda/envs/DRAM/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/karenhn/.conda/envs/DRAM/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/karenhn/.conda/envs/DRAM/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I have no idea what this means! The database_files and the database_processing.log are empty, and I tried 
`DRAM-setup.py export_config --output_file fix_me.txt` but that file is empty too.

Am I missing something obvious? Any help would be appreciated.

**Comment by tpall** [comment]
I ran to same issue. Apparently, DRAM-setup.py lines 123-127 were broken (release v1.5.0):  

https://github.com/WrightonLabCSU/DRAM/blob/7735a04e58c300d53f9d3611a583b48e507bb843/scripts/DRAM-setup.py#L123C5-L127C101

    set_db_locs_parser.add_argument('--viral_loc', default=None,
    set_db_locs_parser.add_argument('--camper_tar_gz_loc', default=None,
                                    help='The source for the CAMPER database files, this is a tar.gz file downloaded'
                                    ' from the release page https://github.com/WrightonLabCSU/CAMPER/releases')
                                    help='mmseqs2 database file from ref seq viral gene collection')

this typo is fixed now with 9ff00c9933723e6d628362b35d486f6dc68709f9, if you install from master.

Thanks DRAM developers!

**Comment by karenhn** [comment]
@tpall  Did you have the same issue with the json.decoder bit too?

**Comment by tpall** [comment]
> @tpall Did you have the same issue with the json.decoder bit too?

No, after installing development version from Github, DRAM-setup.py script runs alright. 

I modified the last line of the environment.yaml file to install from Github.

```
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas=1.5.2
  - pytest=7.2.0
  - scikit-bio=0.5.7
  - prodigal=2.6.3
  - mmseqs2==13.45111
  - hmmer=3.3.2
  - trnascan-se=2.0.11
  - scipy=1.8.1
  - sqlalchemy=1.4.46
  - barrnap=0.9
  - altair=4.2.0
  - openpyxl=3.0.10
  - networkx=2.8.8
  - ruby=3.1.2
  - parallel=20221122
  - pip
  - pip:
    - git+https://github.com/WrightonLabCSU/DRAM.git
```

**Comment by carleton-envbiotech** [comment]
I ended up using the edit provided by @tpall in the environment.yaml, but I could not verify manually in the DRAM-setup.py whether the change took effect. Following the error above for conda, I tried re-creating the environment using mamba and it seems to have fixed the issue and I am setting up the databases from scratch just to make sure the entire setupworkflow is still proceeding.
