### ISSUE TITLE
dbcan2 url gone ?? 

### ISSUE THREAD

**Issue by EricDeveaud** [WrightonLabCSU/DRAM#331]
Hello, 

dbcan2 url seems to be out of service...
since few days. I alway gto.

```
wget http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V11.txt
--2024-02-19 09:06:12--  http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V11.txt
Resolving bcb.unl.edu (bcb.unl.edu)... 129.93.162.49
Connecting to bcb.unl.edu (bcb.unl.edu)|129.93.162.49|:80... failed: Connection timed out.
Retrying.
```

is there any altertnative to get the DRAM's dbcan2 required files ?

regards

Eric

**Comment by carleton-envbiotech** [comment]
I ran into this issue as well, not sure if it is on dbCAN's end or a connectivity issue

**Comment by carleton-envbiotech** [comment]
I tried using the following command where I had the dbCAN databases downloaded from a prior DRAM installation:

`sudo /datastore/tools/gregoire/envs/DRAM/bin/DRAM-setup.py prepare_databases --output_dir /datastore/researchdata/DRAM_data --dbcan_loc '/datastore/researchdata/dram/dbCAN-HMMdb-V11.txt' --dbcan_fam_activities '/datastore/researchdata/dram/CAZyDB.08062022.fam-activities.txt' --threads 40`

And it got past the original error listed above, but it ended up running into an issue with the hmmpress command when starting to process dbCAN (excerpt below):

`2024-02-19 16:23:31,744 - Processing dbcan
Traceback (most recent call last):
  File "/datastore/tools/gregoire/envs/DRAM/bin/DRAM-setup.py", line 187, in <module>
    args.func(**args_dict)
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 615, in prepare_databases
    processed_locs = process_functions[i](locs[i], output_dir, LOGGER,
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 350, in process_dbcan
    run_process(['hmmpress', '-f', output], logger, verbose=verbose)
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 61, in run_process
    results = subprocess.run(command, check=check, shell=shell,
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hmmpress'`

**Comment by carleton-envbiotech** [comment]
This issue seems to have resolved, but it looks like it is downloading v11 when there is a v12 out.
