### ISSUE TITLE
hmmpress not found during prepare_databases

### ISSUE THREAD

**Issue by carleton-envbiotech** [WrightonLabCSU/DRAM#332]
I have been trying to do a new conda install of DRAM on my server but the prepare_databases step keeps running into an error after downloading all of the raw data. The traceback call suggests it cannot find a file or directory for hmmpress:

2024-02-19 20:35:59,539 - Database preparation started
2024-02-19 20:35:59,539 - Downloading kofam_hmm
2024-02-19 20:38:24,912 - Downloading kofam_ko_list
2024-02-19 20:38:27,909 - Downloading uniref
2024-02-19 21:19:03,749 - Downloading pfam
2024-02-19 21:41:05,368 - Downloading pfam_hmm
2024-02-19 21:41:07,041 - Downloading dbcan
2024-02-19 21:41:32,824 - Downloading dbcan_fam_activities
2024-02-19 21:41:32,825 - Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam-activities.txt                                              
2024-02-19 21:41:33,050 - Downloading dbcan_subfam_ec
2024-02-19 21:41:33,051 - Downloading dbCAN sub-family encumber from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam.subfam.ec.txt                                             
2024-02-19 21:41:33,462 - Downloading vogdb
2024-02-19 21:43:04,441 - Downloading vog_annotations
2024-02-19 21:43:05,611 - Downloading viral
2024-02-19 21:43:45,762 - Downloading peptidase
2024-02-19 21:44:57,862 - Downloading genome_summary_form
2024-02-19 21:44:58,130 - Downloading module_step_form
2024-02-19 21:44:58,382 - Downloading function_heatmap_form
2024-02-19 21:44:58,551 - Downloading amg_database
2024-02-19 21:44:58,722 - Downloading etc_module_database
2024-02-19 21:44:58,877 - All raw data files were downloaded successfully
2024-02-19 21:44:58,877 - Processing kofam_hmm
Traceback (most recent call last):
  File "/datastore/tools/gregoire/envs/DRAM/bin/DRAM-setup.py", line 187, in <module>
    args.func(**args_dict)
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 615, in prepare_databases                                                         
    processed_locs = process_functions[i](locs[i], output_dir, LOGGER,
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 246, in process_kofam_hmm                                                         
    run_process(['hmmpress', '-f', merged_kofam_profiles], logger, verbose=verbose)
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 61, in run_process
    results = subprocess.run(command, check=check, shell=shell,
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/datastore/tools/gregoire/envs/DRAM/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hmmpress'

I double checked that hmmpress is in the environment with 'which hmmpress' and it returns that it is in the DRAM environment

`/datastore/tools/gregoire/envs/DRAM/bin/hmmpress`

I am not sure how to address this or whether this stems from edits I had to make to the environmental.yaml to get the initial DRAM environment created properly with mamba to begin with following this post : https://github.com/WrightonLabCSU/DRAM/issues/330

**Comment by BioRRW** [comment]
Thank you for choosing to use DRAM. Unfortunately, at this time, we do not have the capacity to provide support for DRAM. We appreciate your understanding and encourage you to stay tuned for the release of DRAM2, expected in 2025.

Best regards, DRAM dev team
