### ISSUE TITLE
DRAM database installation problem; The subcommand mmseqs createindex DRAM_data/uniref90.20240308.mmsdb DRAM_data/tmp --threads 10 experienced an error

### ISSUE THREAD

**Issue by camillaln** [WrightonLabCSU/DRAM#336]
Hi,

I am having problems installing the DRAM database. I get the same error on two different servers. I installed DRAM following the instructions:

git clone https://github.com/WrightonLabCSU/DRAM.git
cd DRAM
conda create --name dram_env -f environment.yaml
conda activate dram_env
# Install pip
conda install pip3
pip3 install ./

Here is the error:

2024-03-08 18:16:35,301 - Processing uniref

2024-03-08 18:52:57,067 - The subcommand ['mmseqs', 'createindex', 'DRAM_data/uniref90.20240308.mmsdb', 'DRAM_data/tmp', '--threads', '10'] experienced an error: Killed

Traceback (most recent call last):
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/miniconda3/envs/dram_env/bin/DRAM-setup.py", line 187, in <module>
    args.func(**args_dict)
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/miniconda3/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 615, in prepare_databases
    processed_locs = process_functions[i](locs[i], output_dir, LOGGER,
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/miniconda3/envs/dram_env/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 322, in process_uniref
    make_mmseqs_db(uniref_fasta_zipped, uniref_mmseqs_db, logger, create_index=True, threads=threads, verbose=verbose)
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/miniconda3/envs/dram_env/lib/python3.10/site-packages/mag_annotator/utils.py", line 98, in make_mmseqs_db
    run_process(['mmseqs', 'createindex', output_loc, tmp_dir, '--threads', str(threads)], logger, verbose=verbose)
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/miniconda3/envs/dram_env/lib/python3.10/site-packages/mag_annotator/utils.py", line 71, in run_process
    raise subprocess.SubprocessError(f"The subcommand {' '.join(command)} experienced an error, see the log for more info.")
subprocess.SubprocessError: The subcommand mmseqs createindex DRAM_data/uniref90.20240308.mmsdb DRAM_data/tmp --threads 10 experienced an error, see the log for more info.

**Comment by crane90** [comment]
in my case it seems to have run out of working memory, now that i have allocated more working memory for the command it worked fine

**Comment by BioRRW** [comment]
Thank you for choosing to use DRAM. Unfortunately, at this time, we do not have the capacity to provide support for DRAM. We appreciate your understanding and encourage you to stay tuned for the release of DRAM2, expected in 2025.

Best regards, DRAM dev team

**Comment by WhatChan123** [comment]
@crane90 Hi, Can you please show me how to allocate more working memory for the command? I also have the same problem! Thank you!

**Comment by Gsmith535** [comment]
> @crane90 Hi, Can you please show me how to allocate more working memory for the command? I also have the same problem! Thank you!

If you are on a managed cluster, you can try submitting a job that requests between 400 and >512 Gbp of memory (depending on KEGG/uniref inclusion, per documentation on db setup), though this value can likely be lower .

If you are not on a managed cluster, you need to make sure you have at least enough memory to store the databases.

**Comment by Sneakypeat** [comment]
> Thank you for choosing to use DRAM. Unfortunately, at this time, we do not have the capacity to provide support for DRAM. We appreciate your understanding and encourage you to stay tuned for the release of DRAM2, expected in 2025.
> 
> Best regards, DRAM dev team

When can we expect DRAM v2 to be released? RAM running out of memory is not letting new users use DRAM.

**Comment by madeline-scyphers** [comment]
DRAM v2 is in public beta now, and can be found on dev branch. You currently adjust queue size easily, and you can adjust ram requirements if you dig into the config files a bit, but plans to make it easier in the future. We don't have an ETA for the full v2 release yet.
