### ISSUE TITLE
Fail in processing vogdb

### ISSUE THREAD

**Issue by ShangLiii** [WrightonLabCSU/DRAM#341]
I tried a lot of times to install dram (v.1.4.6) but failed at the step of vogdb.
the error is "subprocess.SubprocessError(f"The subcommand {' '.join(command)} experienced an error"
Does anyone know what is the problem and how to fix this?
Here is what I have got:

2024-04-01 14:16:54,384 - Processing vogdb
2024-04-01 14:17:24,864 - The subcommand ['hmmpress', '-f', './DRAM_db/vog_latest_hmms.txt'] experienced an error:
Error: File format problem in trying to open HMM file ./DRAM_db/vog_latest_hmms.txt.
File exists, but appears to be empty?

Traceback (most recent call last):
  File "/data2/lishang/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 184, in <module>
  File "/data2/lishang/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 555, in prepare_databases
  File "/data2/lishang/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 317, in process_vogdb
  File "/data2/lishang/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 71, in run_process
    raise subprocess.SubprocessError(f"The subcommand {' '.join(command)} experienced an error, see the log for more info.")
subprocess.SubprocessError: The subcommand hmmpress -f ./DRAM_db/vog_latest_hmms.txt experienced an error, see the log for more info.

**Comment by yaojian1997** [comment]
I also meet this problem.

**Comment by anbadilla** [comment]
I'm facing the same problem when running DRAM through Atlas-Metagenome.

**Comment by schmigle** [comment]
See my solution here:
https://github.com/WrightonLabCSU/DRAM/issues/340

Seems to be linked to a directory structure mismatch

**Comment by sahilrishav2** [comment]
I also faced the same issue

**Comment by SilasK** [comment]
I think we found an solution to this issue. https://github.com/metagenome-atlas/atlas/issues/718

@WrightonLabAdmin  would it be possible to release a v 1.4.7 with this small fix? It would solve some problems at metagenome atlas.

**Comment by sahilrishav2** [comment]
Actually, i was also able to solve the problem
