### ISSUE TITLE
Problem with database instalation

### ISSUE THREAD

**Issue by Platelmin1o** [WrightonLabCSU/DRAM#342]
I used the following comand to install DRAM database:
`DRAM-setup.py prepare_databases --skip_uniref --output_dir DRAM_db --threads 40`

However I an experiencing problems during instalation with hmmpres. Here is the error message:

/MP_Data/mambaforge/envs/DRAM/lib/python3.11/site-packages/mag_annotator/database_handler.py:126: UserWarning: Database does not exist at path None
  warnings.warn("Database does not exist at path %s" % description_loc)
2024-04-24 18:48:09,361 - Starting the process of downloading data
2024-04-24 18:48:09,361 - Skipping UniRef
2024-04-24 18:48:09,361 - The kegg_loc argument was not used to specify a downloaded kegg file, and dram can not download it its self. So it is assumed that the user wants to set up DRAM without it
2024-04-24 18:48:09,361 - The gene_ko_link_loc argument was not used to specify a downloaded gene_ko_link file, and dram can not download it its self. So it is assumed that the user wants to set up DRAM without it
2024-04-24 18:48:09,361 - Database preparation started
2024-04-24 18:48:09,361 - Downloading kofam_hmm
2024-04-24 18:51:51,271 - Downloading kofam_ko_list
2024-04-24 18:52:23,996 - Downloading pfam
2024-04-24 19:21:55,420 - Downloading pfam_hmm
2024-04-24 19:21:57,290 - Downloading dbcan
2024-04-24 19:22:06,507 - Downloading dbcan_fam_activities
2024-04-24 19:22:06,507 - Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam-activities.txt
2024-04-24 19:22:06,915 - Downloading dbcan_subfam_ec
2024-04-24 19:22:06,915 - Downloading dbCAN sub-family encumber from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam.subfam.ec.txt
2024-04-24 19:22:08,202 - Downloading vogdb
2024-04-24 19:23:24,503 - Downloading vog_annotations
2024-04-24 19:23:25,939 - Downloading viral
2024-04-24 19:24:05,839 - Downloading peptidase
2024-04-24 19:24:51,776 - Downloading genome_summary_form
2024-04-24 19:24:52,166 - Downloading module_step_form
2024-04-24 19:24:52,509 - Downloading function_heatmap_form
2024-04-24 19:24:52,667 - Downloading amg_database
2024-04-24 19:24:52,819 - Downloading etc_module_database
2024-04-24 19:24:53,016 - All raw data files were downloaded successfully
2024-04-24 19:24:53,016 - Processing kofam_hmm
2024-04-24 19:27:08,103 - KOfam database processed
2024-04-24 19:27:08,168 - Moved kofam_hmm to final destination, configuration updated
2024-04-24 19:27:08,168 - Processing kofam_ko_list
2024-04-24 19:27:08,188 - KOfam ko list processed
2024-04-24 19:27:08,189 - Moved kofam_ko_list to final destination, configuration updated
2024-04-24 19:27:08,189 - Processing pfam
2024-04-24 19:50:21,919 - PFAM database processed
2024-04-24 19:50:21,920 - Moved pfam to final destination, configuration updated
2024-04-24 19:50:21,921 - Moved pfam_hmm to final destination, configuration updated
2024-04-24 19:50:21,921 - Processing dbcan
2024-04-24 19:50:23,253 - dbCAN database processed
2024-04-24 19:50:23,259 - Moved dbcan to final destination, configuration updated
2024-04-24 19:50:23,260 - Moved dbcan_fam_activities to final destination, configuration updated
2024-04-24 19:50:23,274 - Moved dbcan_subfam_ec to final destination, configuration updated
2024-04-24 19:50:23,274 - Processing vogdb
2024-04-24 19:50:47,761 - The subcommand ['hmmpress', '-f', 'DRAM_db/vog_latest_hmms.txt'] experienced an error:
Error: File format problem in trying to open HMM file DRAM_db/vog_latest_hmms.txt.
File exists, but appears to be empty?

Traceback (most recent call last):
  File "/MP_Data/mambaforge/envs/DRAM/bin/DRAM-setup.py", line 187, in <module>
    args.func(**args_dict)
  File "/MP_Data/mambaforge/envs/DRAM/lib/python3.11/site-packages/mag_annotator/database_processing.py", line 615, in prepare_databases
    processed_locs = process_functions[i](locs[i], output_dir, LOGGER,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/MP_Data/mambaforge/envs/DRAM/lib/python3.11/site-packages/mag_annotator/database_processing.py", line 377, in process_vogdb
    run_process(['hmmpress', '-f', vog_hmms], logger, verbose=verbose)
  File "/MP_Data/mambaforge/envs/DRAM/lib/python3.11/site-packages/mag_annotator/utils.py", line 71, in run_process
    raise subprocess.SubprocessError(f"The subcommand {' '.join(command)} experienced an error, see the log for more info.")
subprocess.SubprocessError: The subcommand hmmpress -f DRAM_db/vog_latest_hmms.txt experienced an error, see the log for more info.

**Comment by sahilrishav2** [comment]
This link has solved the above mentioned issue

https://github.com/WrightonLabCSU/DRAM/issues/340

**Comment by BioRRW** [comment]
Thank you for choosing to use DRAM. Unfortunately, at this time, we do not have the capacity to provide support for DRAM. We appreciate your understanding and encourage you to stay tuned for the release of DRAM2, expected in 2025.

Best regards, DRAM dev team
