### ISSUE TITLE
pop out errors when prepare databases

### ISSUE THREAD

**Issue by lingc31415** [WrightonLabCSU/DRAM#354]
DRAM-setup.py prepare_databases --skip_uniref --output_dir DRAM_TRIAL1 --threads 10

/lib/python3.9/site-packages/mag_annotator/database_handler.py:126: UserWarning: Database does not exist at path None
  warnings.warn("Database does not exist at path %s" % description_loc)
2024-07-11 11:50:44,888 - Starting the process of downloading data
2024-07-11 11:50:44,889 - Skipping UniRef
2024-07-11 11:50:44,889 - The kegg_loc argument was not used to specify a downloaded kegg file, and dram can not download it its self. So it is assumed that the user wants to set up DRAM without it
2024-07-11 11:50:44,889 - The gene_ko_link_loc argument was not used to specify a downloaded gene_ko_link file, and dram can not download it its self. So it is assumed that the user wants to set up DRAM without it
2024-07-11 11:50:44,889 - Database preparation started
2024-07-11 11:50:44,889 - Downloading kofam_hmm
2024-07-11 11:52:51,434 - Downloading kofam_ko_list
2024-07-11 11:52:55,108 - Downloading pfam
2024-07-11 11:54:42,311 - Downloading pfam_hmm
2024-07-11 11:54:42,453 - Downloading dbcan
2024-07-11 11:54:47,652 - Downloading dbcan_fam_activities
2024-07-11 11:54:47,652 - Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam-activities.txt
2024-07-11 11:54:48,237 - Downloading dbcan_subfam_ec
2024-07-11 11:54:48,237 - Downloading dbCAN sub-family encumber from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam.subfam.ec.txt
2024-07-11 11:54:49,162 - Downloading vogdb
2024-07-11 11:54:57,971 - Downloading vog_annotations
2024-07-11 11:54:58,275 - Downloading viral
2024-07-11 11:55:03,478 - Downloading peptidase
2024-07-11 11:55:05,171 - Downloading genome_summary_form
2024-07-11 11:55:05,435 - Downloading module_step_form
2024-07-11 11:55:05,715 - Downloading function_heatmap_form
2024-07-11 11:55:05,972 - Downloading amg_database
2024-07-11 11:55:06,201 - Downloading etc_module_database
2024-07-11 11:55:06,442 - All raw data files were downloaded successfully
2024-07-11 11:55:06,443 - Processing kofam_hmm
2024-07-11 11:58:24,529 - KOfam database processed
2024-07-11 11:58:24,637 - Moved kofam_hmm to final destination, configuration updated
2024-07-11 11:58:24,637 - Processing kofam_ko_list
2024-07-11 11:58:24,816 - KOfam ko list processed
2024-07-11 11:58:24,828 - Moved kofam_ko_list to final destination, configuration updated
2024-07-11 11:58:24,829 - Processing pfam
2024-07-11 13:35:29,629 - PFAM database processed
2024-07-11 13:35:29,646 - Moved pfam to final destination, configuration updated
2024-07-11 13:35:29,657 - Moved pfam_hmm to final destination, configuration updated
2024-07-11 13:35:29,657 - Processing dbcan
2024-07-11 13:35:31,548 - dbCAN database processed
2024-07-11 13:35:31,560 - Moved dbcan to final destination, configuration updated
2024-07-11 13:35:31,570 - Moved dbcan_fam_activities to final destination, configuration updated
2024-07-11 13:35:31,579 - Moved dbcan_subfam_ec to final destination, configuration updated
2024-07-11 13:35:31,580 - Processing vogdb
2024-07-11 13:36:55,363 - The subcommand ['hmmpress', '-f', 'DRAM_TRIAL1/vog_latest_hmms.txt'] experienced an error: 
Error: File format problem in trying to open HMM file DRAM_TRIAL1/vog_latest_hmms.txt.
File exists, but appears to be empty?

Traceback (most recent call last):
  File "/shared/team/conda/bin/DRAM-setup.py", line 187, in <module>
    args.func(**args_dict)
  File "/shared/team/conda/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 615, in prepare_databases
    processed_locs = process_functions[i](locs[i], output_dir, LOGGER,
  File "/shared/team/conda/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 377, in process_vogdb
    run_process(['hmmpress', '-f', vog_hmms], logger, verbose=verbose)
  File "/shared/team/conda/lib/python3.9/site-packages/mag_annotator/utils.py", line 71, in run_process
    raise subprocess.SubprocessError(f"The subcommand {' '.join(command)} experienced an error, see the log for more info.")
subprocess.SubprocessError: The subcommand hmmpress -f DRAM_TRIAL1/vog_latest_hmms.txt experienced an error, see the log for more info.

jovyan:~/ ll DRAM_TRIAL1/
total 140086528

-rw-r--r--  1 jovyan users        21569 Jul 11 11:55 amg_database.20240711.tsv
-rw-r--r--  1 jovyan users        71475 Jul 11 11:54 CAZyDB.08062022.fam-activities.txt
-rw-r--r--  1 jovyan users        666757 Jul 11 11:54 CAZyDB.08062022.fam.subfam.ec.txt
drwxr-xr-x  2 jovyan users        7 Jul 11 13:35 database_files/
-rw-r--r--  1 jovyan users         3064 Jul 11 13:36 database_processing.log
-rw-r--r--  1 jovyan users    100919249 Jul 11 11:54 dbCAN-HMMdb-V11.txt
-rw-r--r--  1 jovyan users     18500973 Jul 11 13:35 dbCAN-HMMdb-V11.txt.h3f
-rw-r--r--  1 jovyan users        35391 Jul 11 13:35 dbCAN-HMMdb-V11.txt.h3i
-rw-r--r--  1 jovyan users     42008390 Jul 11 13:35 dbCAN-HMMdb-V11.txt.h3m
-rw-r--r--  1 jovyan users     49352187 Jul 11 13:35 dbCAN-HMMdb-V11.txt.h3p
-rw-r--r--  1 jovyan users         2378 Jul 11 11:55 etc_mdoule_database.20240711.tsv
-rw-r--r--  1 jovyan users        11199 Jul 11 11:55 function_heatmap_form.20240711.tsv
-rw-r--r--  1 jovyan users       580242 Jul 11 11:55 genome_summary_form.20240711.tsv
-rw-r--r--  1 jovyan users      2705990 Jul 11 11:58 kofam_ko_list.tsv
drwxr-xr-x  3 jovyan users            1 Jul 11 11:55 kofam_profiles/
-rw-r--r--  1 jovyan users   7242069514 Jul 11 11:56 kofam_profiles.hmm
-rw-r--r--  1 jovyan users   1122768880 Jul 11 11:58 kofam_profiles.hmm.h3f
-rw-r--r--  1 jovyan users       865847 Jul 11 11:58 kofam_profiles.hmm.h3i
-rw-r--r--  1 jovyan users   3003152169 Jul 11 11:58 kofam_profiles.hmm.h3m
-rw-r--r--  1 jovyan users   3523167986 Jul 11 11:58 kofam_profiles.hmm.h3p
-rw-r--r--  1 jovyan users       579664 Jul 11 11:55 module_step_form.20240711.tsv
-rw-r--r--  1 jovyan users       586696 Jul 11 11:54 Pfam-A.hmm.dat.gz
-rw-r--r--  1 jovyan users 122422951744 Jul 11 12:17 pfam.mmsmsa
-rw-r--r--  1 jovyan users            4 Jul 11 12:17 pfam.mmsmsa.dbtype
-rw-r--r--  1 jovyan users       534727 Jul 11 12:17 pfam.mmsmsa.index
-rw-r--r--  1 jovyan users    128927770 Jul 11 13:34 pfam.mmspro
-rw-r--r--  1 jovyan users            4 Jul 11 13:34 pfam.mmspro.dbtype
-rw-r--r--  1 jovyan users       758327 Jul 11 13:34 pfam.mmspro_h
-rw-r--r--  1 jovyan users            4 Jul 11 13:34 pfam.mmspro_h.dbtype
-rw-r--r--  1 jovyan users       335213 Jul 11 13:34 pfam.mmspro_h.index
-rw-r--r--  1 jovyan users   5786103808 Jul 11 13:35 pfam.mmspro.idx
-rw-r--r--  1 jovyan users            4 Jul 11 13:35 pfam.mmspro.idx.dbtype
-rw-r--r--  1 jovyan users          335 Jul 11 13:35 pfam.mmspro.idx.index
-rw-r--r--  1 jovyan users       431683 Jul 11 13:34 pfam.mmspro.index
drwxr-xr-x  3 jovyan users            2 Jul 11 13:34 tmp/
-rw-r--r--  1 jovyan users       481712 Jul 11 11:54 vog_annotations_latest.tsv.gz
drwxr-xr-x  3 jovyan users            1 Jul 11 13:35 vogdb_hmms/
-rw-r--r--  1 jovyan users            0 Jul 11 13:36 vog_latest_hmms.txt

**Comment by bioverne** [comment]
how do you solve the problem?i am facing with the same err just like yours.

**Comment by Leytoncito** [comment]
x1000 the same error GG
