### ISSUE TITLE
set_database_locations results in TypeError: DatabaseHandler.set_database_paths() got an unexpected keyword argument 'camper_tar_gz_loc'

### ISSUE THREAD

**Issue by jehalter0** [WrightonLabCSU/DRAM#355]
When I try to set the pfam_hmm_loc using the following command:

$ DRAM-setup.py set_database_locations --pfam_hmm_loc /projects/datasets/dram/1.5.0/Pfam-A.hmm.dat.gz

I get the following TypeError, complaining about an unexpected keyword argument "camper_tar_gz_loc":

2024-07-25 09:19:32,281 - Logging to console
Traceback (most recent call last):
  File "/apps/pkg/anaconda3/envs/dram-1.5.0/bin/DRAM-setup.py", line 186, in <module>
    args.func(**args_dict)
  File "/apps/pkg/anaconda3/envs/dram-1.5.0/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 582, in set_database_paths
    db_handler.set_database_paths(**kargs, write_config=True)
TypeError: DatabaseHandler.set_database_paths() got an unexpected keyword argument 'camper_tar_gz_loc'

**Comment by Xuyang-Feng** [comment]
hi，I met the same problem when I try to set the genome_summary_form locations.  Do you find the solutions to solve this problem? Thank  you!
