### ISSUE TITLE
Database download interrupted

### ISSUE THREAD

**Issue by baidefeng** [WrightonLabCSU/DRAM#392]
An error occurred during the database download process, is there anyone know how to fix it?

/data5/baidefeng/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:126: UserWarning: Database does not exist at path None
  warnings.warn("Database does not exist at path %s" % description_loc)
2024-12-15 20:50:15,835 - Starting the process of downloading data
2024-12-15 20:50:15,835 - The kegg_loc argument was not used to specify a downloaded kegg file, and dram can not download it its self. So it is assumed that the user wants to set up DRAM without it
2024-12-15 20:50:15,835 - The gene_ko_link_loc argument was not used to specify a downloaded gene_ko_link file, and dram can not download it its self. So it is assumed that the user wants to set up DRAM without it
2024-12-15 20:50:15,835 - Database preparation started
2024-12-15 20:50:15,835 - Downloading kofam_hmm
2024-12-16 01:40:50,265 - Downloading kofam_ko_list
2024-12-16 01:40:54,414 - Downloading uniref
2024-12-17 06:53:56,976 - Downloading pfam
2024-12-17 11:54:54,661 - Downloading pfam_hmm
2024-12-17 11:54:57,444 - Downloading dbcan
2024-12-17 12:03:24,002 - Downloading dbcan_fam_activities
2024-12-17 12:03:24,002 - Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam-activities.txt
2024-12-17 12:03:25,573 - Downloading dbcan_subfam_ec
2024-12-17 12:03:25,573 - Downloading dbCAN sub-family encumber from : https://bcb.unl.edu/dbCAN2/download/Databases/V11/CAZyDB.08062022.fam.subfam.ec.txt
2024-12-17 12:03:29,276 - Downloading vogdb
2024-12-17 12:14:06,856 - Downloading vog_annotations
2024-12-17 12:14:09,575 - Downloading viral
2024-12-17 12:15:36,975 - Downloading peptidase
2024-12-17 12:24:04,223 - Downloading genome_summary_form
2024-12-17 12:24:04,290 - Something went wrong with the download of the url: https://raw.githubusercontent.com/WrightonLabCSU/DRAM/master/data/genome_summary_form.tsv
2024-12-17 12:24:04,291 - <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/data5/baidefeng/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 187, in <module>
    args.func(**args_dict)
  File "/data5/baidefeng/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 595, in prepare_databases
    locs[i] = download_functions[i](
  File "/data5/baidefeng/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 391, in download_genome_summary_form
    download_file('https://raw.githubusercontent.com/WrightonLabCSU/DRAM/%s/data/genome_summary_form.tsv' % branch,
  File "/data5/baidefeng/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 33, in download_file
    raise URLError("DRAM whas not able to download a key database, check the logg for details")
urllib.error.URLError: <urlopen error DRAM whas not able to download a key database, check the logg for details>

**Comment by jiaojiaoguan** [comment]
If you already have any of the databases downloaded to your server and don't want to download them again then you can pass them to the prepare_databases command by use the --{db_name}_loc flags such as --uniref_loc and --viral_loc.

**Comment by Hundred56** [comment]
I am experiencing the same problm as you. Have you solved it?

**Comment by Cczyf** [comment]
the same problm as you. Have you solved it?

**Comment by YanjieZhu1997** [comment]
> If you already have any of the databases downloaded to your server and don't want to download them again then you can pass them to the prepare_databases command by use the --{db_name}_loc flags such as --uniref_loc and --viral_loc.

Those flags don't work for me. Even when the path to an existing database was indicated, it still tried to download the database, and then showed 'Something went wrong with the download of the url...'
