### ISSUE TITLE
DRAM-setup.py prepare databases error "non-zero exit status 1"

### ISSUE THREAD

**Issue by RVTrexler** [WrightonLabCSU/DRAM#5]
Hi Mike,

I'm looking forward to using DRAM, but I'm having an issue at the 'DRAM-setup.py prepare_databases' step. I hope I'm not missing something simple on my end. I am running in a conda environment. Happy to provide any other information you might need.

Thanks!

Ryan

See below:

(DRAM) [rxt92@aci-lgn-004 DRAM]$ DRAM-setup.py prepare_databases --output_dir DRAM_data --threads 10
2020-05-04 10:31:39.177381: Database preparation started
Traceback (most recent call last):
  File "/storage/home/rxt92/.conda/envs/DRAM/bin/DRAM-setup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/scripts/DRAM-setup.py", line 136, in <module>
    args.func(**args_dict)
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/database_processing.py", line 443, in prepare_databases
    output_dbs['uniref_db_loc'] = download_and_process_uniref(uniref_loc, temporary, uniref_version=uniref_version,
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/database_processing.py", line 112, in download_and_process_uniref
    make_mmseqs_db(uniref_fasta_zipped, uniref_mmseqs_db, create_index=True, threads=threads, verbose=verbose)
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/utils.py", line 45, in make_mmseqs_db
    run_process(['mmseqs', 'createdb', fasta_loc, output_loc], verbose=verbose)
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/utils.py", line 37, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/storage/home/rxt92/.conda/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createdb', 'DRAM_data/database_files/uniref90.fasta.gz', 'DRAM_data/database_files/uniref90.20200504.mmsdb']' returned non-zero exit status 1.

**Comment by shafferm** [comment]
Hi Ryan,

A few questions. How much RAM does your system have? To process the uniref database you need ~512 GB of RAM. Also what version of DRAM are you using? Did you install via pip or directly from the github repository? The current version on pip has a known issue during set up which is fixed in master. A new version should be pushed to pip which fixes this issue in the next week or so.

If you are using a big node and are on the github master branch version then can you try running the command `mmseqs createdb DRAM_data/database_files/uniref90.fasta.gz DRAM_data/database_files/uniref90.20200504.mmsdb` directly on the command line and let me know what it says?

Mike

**Comment by RVTrexler** [comment]
Hi Mike,

Thanks for the quick reply. Depending on the node type requested our system has either 128 GB, 256 GB, or 1TB of RAM available per node. I'm not quite sure how this works though because I'm not requesting any work nodes (e.g. submitting batch script) and I'm (presumably) running on a head node. I can try to figure this out though if it might be an issue.

I believe I am using the most current DRAM version as of last evening. I created the DRAM conda env and installed dependencies via conda using the .yaml file from github, and cloned DRAM via `git clone https://github.com/shafferm/DRAM.git`, yesterday. In the DRAM conda environment and in the downloaded DRAM folder from `git clone` above, I ran `pip install -e .`.

I tried looking for the version, but not sure where I can find it. I installed pip when creating the conda environment with the .yaml file.

`(DRAM) [rxt92@aci-lgn-004 DRAM]$ which pip
~/.conda/envs/DRAM/bin/pip`

`conda list` returns: pip 20.1 pyh9f0ad1d_0 conda-forge

As you suggested I ran `mmseqs createdb DRAM_data/database_files/uniref90.fasta.gz DRAM_data/database_files/uniref90.20200504.mmsdb`

It looks like it ran smoothly and returns the following:

(DRAM) [rxt92@aci-lgn-004 DRAM]$ mmseqs createdb DRAM_data/database_files/uniref90.fasta.gz DRAM_data/database_files/uniref90.20200504.mmsdb
createdb DRAM_data/database_files/uniref90.fasta.gz DRAM_data/database_files/uniref90.20200504.mmsdb 

MMseqs Version:       	11.e1a1c

Converting sequences
[109653883] 16m 34s 691ms
Time for merging to uniref90.20200504.mmsdb_h: 0h 5m 58s 939ms
Time for merging to uniref90.20200504.mmsdb: 0h 8m 57s 472ms
Database type: Aminoacid
Time for merging to uniref90.20200504.mmsdb.lookup: 0h 0m 0s 27ms
Time for processing: 0h 35m 21s 500ms

**Comment by RVTrexler** [comment]
Hi Mike,

Just wanted to update in case it might be helpful:

I traced the error flag back to utils.py line 29, `def run_process(command, shell=False, capture_stdout=True, check=True, verbose=False)`, so I decided to try out manually modifying `check=True` to `check=False` to see what might happen.

In this case, DRAM-setup.py is able to move past the error (not sure whether it was solved or just ignored) and process all of the databases, but then I receive a different error in the "Setting database paths" step - see below. It looks like not all of the files in "..DRAM_data/database_files" are moved over to "..DRAM_data", including "pfam.mmspro", which is causing the new error.

I attached the output of `(DRAM) [rxt92@aci-lgn-006 DRAM]$ ls /storage/home/rxt92/scratch/DRAM_data/`, `(DRAM) [rxt92@aci-lgn-006 DRAM]$ ls -l /storage/home/rxt92/scratch/DRAM_data/database_files/`, and `conda list`. I'm happy to send anything else your way. Also, I wanted to confirm that I was using commit 0a35a4a and also see the "non-zero exit status 1" error on commit 3e540cf.

[Conda_list.txt](https://github.com/shafferm/DRAM/files/4604103/Conda_list.txt)
[DRAM_data.database_files.txt](https://github.com/shafferm/DRAM/files/4604104/DRAM_data.database_files.txt)
[DRAM_data.txt](https://github.com/shafferm/DRAM/files/4604105/DRAM_data.txt)


(DRAM) [rxt92@aci-lgn-006 DRAM]$ DRAM-setup.py prepare_databases --output_dir ~/scratch/DRAM_data
2020-05-08 18:47:40.739569: Database preparation started
2:36:11.197811: UniRef database processed
4:29:36.009697: PFAM database processed
4:29:47.337359: dbCAN database processed
4:30:00.114370: RefSeq viral database processed
4:31:02.988212: MEROPS database processed
4:40:08.331283: VOGdb database processed
4:54:52.427269: KOfam database processed
4:55:00.438079: KOfam ko list processed
4:55:02.815637: PFAM hmm dat processed
4:55:03.099338: dbCAN fam activities processed
4:55:04.293696: VOGdb annotations processed
4:55:05.725613: DRAM databases and forms downloaded
4:55:05.882635: Files moved to final destination
4:55:05.882866: Setting database paths
Traceback (most recent call last):
  File "/storage/home/rxt92/.conda/envs/DRAM/bin/DRAM-setup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/scripts/DRAM-setup.py", line 136, in <module>
    args.func(**args_dict)
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/database_processing.py", line 512, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/database_processing.py", line 331, in set_database_paths
    db_dict = check_exists_and_add_to_location_dict(pfam_db_loc, 'pfam', db_dict)
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/database_processing.py", line 299, in check_exists_and_add_to_location_dict
    if check_file_exists(loc):
  File "/storage/work/r/rxt92/conda_local/envs/DRAM/DRAM/mag_annotator/database_processing.py", line 34, in check_file_exists
    raise ValueError("Database location does not exist: %s" % db_loc)
ValueError: Database location does not exist: /storage/home/rxt92/scratch/DRAM_data/pfam.mmspro

**Comment by shafferm** [comment]
Thanks for digging into this more Ryan. If uniref worked then pfam should work too which rules out memory. First step could be to try to rerun and make sure it wasn't something more random or we can try to dig deeper.

By setting check to false all that happened was that the error was allowed to happen in the background and not stop the rest of execution. Everything else seems like it worked based on your ls output.

Let's try running the Pfam steps that DRAM is running under the hood directly.

```bash
wget ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz
mmseqs convertmsa Pfam-A.full.gz pfam.mmsmsa
mmseqs msa2profile pfam.mmsmsa pfam.mmspro --match-mode 1 --threads {threads}
mmseqs createindex pfam.mmspro tmp_dir -k 5 -s 7 --threads {threads}
```

Just replace `{threads}` with the number of processors you want to use.

**Comment by RVTrexler** [comment]
When I run this on the command line after about 2 hrs or so I get a 'killed' error during the `mmseqs msa2profile pfam.mmsmsa pfam.mmspro --match-mode 1 --threads {threads}` step. See here: 
[DRAM_Pfam_MMseqs2_test.txt](https://github.com/shafferm/DRAM/files/4635308/DRAM_Pfam_MMseqs2_test.txt)


I'm wondered if it was being killed by the head node for taking too many resources, so I submitted this as a job and requested 24 threads and 250gb of memory. I believe it worked in this case. See the output below:
[DRAM_Pfam_MMseqs2_test_pbs.txt](https://github.com/shafferm/DRAM/files/4635349/DRAM_Pfam_MMseqs2_test_pbs.txt)
[DRAM_Pfam_MMseqs2_test_ls.txt](https://github.com/shafferm/DRAM/files/4635364/DRAM_Pfam_MMseqs2_test_ls.txt)

I am currently trying to run the entire dram setup step via a pbs job with requested resources and can let you know how it goes.

Thanks again for your support.

Ryan

**Comment by RVTrexler** [comment]
I'm still getting a 'killed' error when submitting as a job.

"/var/spool/torque/mom_priv/jobs/18711244.torque01.util.production.int.aci.ics.psu.edu.SC: line 26: 103801 Killed"

It looks like all the pfam database files are created, but the files "pfam.mmsmsa", "pfam.mmsmsa.dbtype", "pfam.mmsmsa.index" are not being moved from "./DRAM_data/database_files" to "./DRAM_data". There are also other files that aren't being moved as well.

[ls_DRAM_data_database_files.txt](https://github.com/shafferm/DRAM/files/4638570/ls_DRAM_data_database_files.txt)
[ls_DRAM_data.txt](https://github.com/shafferm/DRAM/files/4638571/ls_DRAM_data.txt)

**Comment by RVTrexler** [comment]
Hi Mike,

Just to update: I am no longer getting a "killed" error when submitting `DRAM-setup.py prepare_databases` as a batch job with 600gb of memory, so it's possible that was a memory error on my end. However, it does not seem to want to finish, even after running for 24 hours with 24 threads. It looks to me like all of the files have been created and processed with the exception of two files: "Pfam-A.hmm.dat.gz" and "vog_annotations_latest.tsv.gz", which aren't being unzipped. I gunzipped them and then ran the following command to add them to the CONFIG file and to update the description database.

`DRAM-setup.py set_database_locations --kofam_hmm_loc /storage/home/rxt92/scratch/DRAM_data/kofam_profiles.hmm --kofam_ko_list_loc /storage/home/rxt92/scratch/DRAM_data/kofam_ko_list.tsv --uniref_db_loc /storage/home/rxt92/scratch/DRAM_data/uniref90.20200609.mmsdb --pfam_db_loc /storage/home/rxt92/scratch/DRAM_data/pfam.mmspro --pfam_hmm_dat /storage/home/rxt92/scratch/DRAM_data/Pfam-A.hmm.dat --dbcan_db_loc /storage/home/rxt92/scratch/DRAM_data/dbCAN-HMMdb-V8.txt --dbcan_fam_activities /storage/home/rxt92/scratch/DRAM_data/CAZyDB.07312019.fam-activities.txt --vogdb_db_loc /storage/home/rxt92/scratch/DRAM_data/vog_latest_hmms.txt --vog_annotations /storage/home/rxt92/scratch/DRAM_data/vog_annotations_latest.tsv --viral_db_loc /storage/home/rxt92/scratch/DRAM_data/refseq_viral.20200609.mmsdb --peptidase_db_loc /storage/home/rxt92/scratch/DRAM_data/peptidases.20200609.mmsdb --genome_summary_form_loc /storage/home/rxt92/scratch/DRAM_data/genome_summary_form.20200609.tsv --module_step_form_loc /storage/home/rxt92/scratch/DRAM_data/module_step_form.20200609.tsv --etc_module_database_loc /storage/home/rxt92/scratch/DRAM_data/etc_mdoule_database.20200609.tsv --function_heatmap_form_loc /storage/home/rxt92/scratch/DRAM_data/function_heatmap_form.20200609.tsv --amg_database_loc /storage/home/rxt92/scratch/DRAM_data/amg_database.20200609.tsv --update_description_db`

Using 600gb of memory, this fails to complete in 12 hours, which seems odd.

Just wondering if you had any thoughts?

Thanks,

Ryan

**Comment by npavlovikj** [comment]
I am encountering the same issue as Ryan when setting the database location in the config file - I requested 500GB of RAM, and for the last 7 hours, the log has been stuck at:
```
0:00:00.000014: Setting database paths
0:00:00.010060: Database locations added to CONFIG
0:00:00.442873: Database connection established
0:00:00.443260: KEGG descriptions added to description database
```

Additionally, downloading the data with `DRAM-setup.py prepare_databases --output_dir DRAM_data` took more than 4 days and 10 hours.

I would really appreciate any assistance with the `set_database_locations` issue.

**Comment by eawebb** [comment]
HI 

DRAM looks really useful! but i cannot seem to get the Db installed. Conda install worked fine for DRAM, but i just got this error on centos HPC trying to install the DBs.  I dont have access to KEGG, so i used this command. also the node that i was running it on has ~1Tb of RAM.

DRAM-setup.py prepare_databases --output_dir /scratch/eawebb/dram/DRAM_data --skip_uniref ---threads 36

error:
Traceback (most recent call last):
  File "/scratch/eawebb/miniconda/envs/DRAM/bin/DRAM-setup.py", line 144, in <module>
    args.func(**args_dict)
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 446, in prepare_databases
    output_dbs['pfam_db_loc'] = download_and_process_pfam(pfam_loc, temporary,
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 131, in download_and_process_pfam
    download_file('ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz', pfam_full_zipped,
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 26, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 37, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', '/scratch/eawebb/dram/DRAM_data/database_files/Pfam-A.full.gz', 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz']' returned non-zero exit status 4.

Any ideas?

**Comment by eawebb** [comment]
hi ryan,

i went ahead downloaded Pfam-A.full.gz and uniref90.fasta.gz myself.  Then i specified their locations.  all seems to have gone well, but then i got this error. This node has >512 RAM.

thanks
e


 File "/scratch/eawebb/miniconda/envs/DRAM/bin/DRAM-setup.py", line 144, in <module>
    args.func(**args_dict)
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 446, in prepare_databases
    output_dbs['pfam_db_loc'] = download_and_process_pfam(pfam_loc, temporary,
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 133, in download_and_process_pfam
    pfam_profile = process_mmspro(pfam_full_zipped, output_dir, 'pfam', threads, verbose)
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 120, in process_mmspro
    run_process(['mmseqs', 'msa2profile', mmseqs_msa, mmseqs_profile, '--match-mode', '1', '--threads', str(threads)],
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 37, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'msa2profile', '/scratch/eawebb/dram/DRAM_data/database_files/pfam.mmsmsa', '/scratch/eawebb/dram/DRAM_data/database_files/pfam.mmspro', '--match-mode', '1', '--threads', '36']' died with <Signals.SIGABRT: 6>.

**Comment by RVTrexler** [comment]
Hi again Mike,

I am still having trouble setting up the DRAM databases and wanted to send an update your way.

When I run `DRAM-setup.py prepare_databases --threads 10 --output_dir /gpfs/group/efc5279/default/ryan/DRAM_db_full/` on our HPC (1TB of available RAM) the process peaks at ~245gb of used memory and stalls. DRAM successfully processes each database (including uniref) with mmseqs, but then stalls when populating the qslite description database. The description_db.sqlite file populates to ~4.8gb which is when memory stalls at ~245gb, and from that point there is no activity until the process exceeds the walltime limit (48hrs). We have been able to complete the entire database set up without uniref, so this occurs only when including uniref.

I have tried the workaround described in https://github.com/shafferm/DRAM/issues/26#issuecomment-685212290, but had no success (I observed the same issue with stalling memory note above). I have been able to successfully prepare the databases without uniref.

It seems like others are also observing this issue and so I wanted to mention some info from our technical staff: 

"One thing I noticed when I was running this was the process remained in 'D' state for very long periods of time. this indicates the process was blocked waiting on resources to become free. If the node is unintentionally memory starving the thread this resource issue could be swap."

and

"I asked some of the systems' folks to get involved so they can see if it is related to any i/o issues to something else." (I am still waiting to hear back regarding i/o)

**Comment by rmFlynn** [comment]
This is old enough, and forgotten enough, that I think I can close this issue. Let me know if you are still experiencing the problem. I suspect an I/O issue.
